//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromedaDataAccessEntityFramework.Model.AndroAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.Stores = new HashSet<Store>();
        }
    
        public int Id { get; set; }
        public string Org1 { get; set; }
        public string Org2 { get; set; }
        public string Org3 { get; set; }
        public string Prem1 { get; set; }
        public string Prem2 { get; set; }
        public string Prem3 { get; set; }
        public string Prem4 { get; set; }
        public string Prem5 { get; set; }
        public string Prem6 { get; set; }
        public string RoadNum { get; set; }
        public string RoadName { get; set; }
        public string Locality { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        public string PostCode { get; set; }
        public string DPS { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public System.Data.Spatial.DbGeography Location { get; set; }
        public int DataVersion { get; set; }
        public int CountryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<Store> Stores { get; set; }
    }
}
