//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.Model.MyAndromeda
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyAndromedaDbContext : DbContext
    {
        public MyAndromedaDbContext()
            : base("name=MyAndromedaDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmailCampaign> EmailCampaigns { get; set; }
        public virtual DbSet<EmailCampaignAudit> EmailCampaignAudits { get; set; }
        public virtual DbSet<EmailCampaignSentEmail> EmailCampaignSentEmails { get; set; }
        public virtual DbSet<EmailCampaignSetting> EmailCampaignSettings { get; set; }
        public virtual DbSet<EmailCampaignSite> EmailCampaignSites { get; set; }
        public virtual DbSet<EmailCampaignTask> EmailCampaignTasks { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserChain> UserChains { get; set; }
        public virtual DbSet<UserRecord> UserRecords { get; set; }
        public virtual DbSet<UserStore> UserStores { get; set; }
        public virtual DbSet<EnrolmentLevel> EnrolmentLevels { get; set; }
        public virtual DbSet<MenuItemInGroup> MenuItemInGroups { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<StoreEnrolment> StoreEnrolments { get; set; }
        public virtual DbSet<RolePermissions> RolePermissions { get; set; }
        public virtual DbSet<CloudSynchronizationTask> CloudSynchronizationTasks { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<StoreEmployee> StoreEmployees { get; set; }
        public virtual DbSet<UserIpLock> UserIpLocks { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<MenuItemThumbnail> MenuItemThumbnails { get; set; }
        public virtual DbSet<SiteMenu> SiteMenus { get; set; }
        public virtual DbSet<SiteMenuFtpBackupDownloadTask> SiteMenuFtpBackupDownloadTasks { get; set; }
        public virtual DbSet<SiteMenuFtpBackupUploadTask> SiteMenuFtpBackupUploadTasks { get; set; }
        public virtual DbSet<SiteMenuMediaProfile> SiteMenuMediaProfiles { get; set; }
        public virtual DbSet<SiteMenuMediaProfileSize> SiteMenuMediaProfileSizes { get; set; }
        public virtual DbSet<SiteMenuMediaServer> SiteMenuMediaServers { get; set; }
        public virtual DbSet<SiteMenuPublishTask> SiteMenuPublishTasks { get; set; }
        public virtual DbSet<SiteMenuPublishTaskHistory> SiteMenuPublishTaskHistories { get; set; }
        public virtual DbSet<SiteMenuMediaServerAuthentication> SiteMenuMediaServerAuthentications { get; set; }
        public virtual DbSet<MarketingContact> MarketingContacts { get; set; }
        public virtual DbSet<MarketingEventCampaign> MarketingEventCampaigns { get; set; }
    }
}
