//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.Model.MyAndromeda
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMenuFtpBackupDownloadTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiteMenuFtpBackupDownloadTask()
        {
            this.SiteMenus = new HashSet<SiteMenu>();
        }
    
        public int Id { get; set; }
        public bool TryTask { get; set; }
        public bool TaskStarted { get; set; }
        public bool TaskCompleted { get; set; }
        public Nullable<System.DateTime> LastTriedUtc { get; set; }
        public int LastTryCount { get; set; }
        public Nullable<System.DateTime> LastStartedUtc { get; set; }
        public Nullable<System.DateTime> LastCompletedUtc { get; set; }
        public Nullable<System.DateTime> LastModifiedFtpDateUtc { get; set; }
        public Nullable<System.DateTime> LastDownloadedDateUtc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteMenu> SiteMenus { get; set; }
    }
}
