//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.DailyReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit
    {
        public int AuditID { get; set; }
        public Nullable<int> nStoreID { get; set; }
        public Nullable<int> n_RefNum { get; set; }
        public Nullable<int> n_EventType { get; set; }
        public Nullable<System.DateTime> d_Date { get; set; }
        public Nullable<int> n_Employee { get; set; }
        public Nullable<int> n_OrderNum { get; set; }
        public Nullable<int> n_MachineID { get; set; }
        public string str_field1 { get; set; }
        public string str_field2 { get; set; }
        public string str_field3 { get; set; }
        public string str_field4 { get; set; }
        public Nullable<int> n_field1 { get; set; }
        public Nullable<int> n_field2 { get; set; }
        public Nullable<int> n_field3 { get; set; }
        public Nullable<int> n_field4 { get; set; }
        public Nullable<int> n_field5 { get; set; }
        public Nullable<int> n_field6 { get; set; }
        public Nullable<System.DateTime> d_Date1 { get; set; }
        public Nullable<System.DateTime> d_Date2 { get; set; }
        public Nullable<System.DateTime> TheDate { get; set; }
    }
}
