//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.DailyReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class createorder
    {
        public Nullable<System.Guid> recordid { get; set; }
        public int autoid { get; set; }
        public int nstoreid { get; set; }
        public int n_ordernum { get; set; }
        public string str_orderaddressnotes { get; set; }
        public Nullable<int> n_takerid { get; set; }
        public Nullable<int> n_cashierid { get; set; }
        public Nullable<int> n_mgrid { get; set; }
        public Nullable<int> n_serverid { get; set; }
        public Nullable<int> n_orderpricegross { get; set; }
        public Nullable<int> n_orderpricenet { get; set; }
        public Nullable<System.DateTime> n_orderplacedtime { get; set; }
        public Nullable<System.DateTime> n_ordermadetime { get; set; }
        public Nullable<System.DateTime> n_ordercuttime { get; set; }
        public Nullable<System.DateTime> n_orderdispatchedtime { get; set; }
        public Nullable<System.DateTime> n_ordercashedtime { get; set; }
        public Nullable<int> n_statusflags { get; set; }
        public Nullable<int> n_occasion { get; set; }
        public Nullable<int> n_orderdiscounttype { get; set; }
        public Nullable<int> n_orderdiscount { get; set; }
        public Nullable<int> n_vatcost { get; set; }
        public Nullable<int> n_totaltime { get; set; }
        public Nullable<int> n_printstart { get; set; }
        public Nullable<int> n_categories { get; set; }
        public Nullable<int> n_drivetime { get; set; }
        public Nullable<int> n_paytype { get; set; }
        public Nullable<int> n_EstimatedTotalTime { get; set; }
        public Nullable<int> n_LoyaltyDiscount { get; set; }
        public Nullable<int> n_PointsRedeemed { get; set; }
        public string str_LoyaltyCard { get; set; }
        public Nullable<int> n_PriceA { get; set; }
        public Nullable<int> n_PriceB { get; set; }
        public Nullable<int> n_PriceC { get; set; }
        public Nullable<int> n_TaxA { get; set; }
        public Nullable<int> n_TaxB { get; set; }
        public Nullable<int> n_TaxC { get; set; }
        public Nullable<int> n_cardid { get; set; }
        public string str_chefnotes { get; set; }
        public Nullable<System.DateTime> thedate { get; set; }
        public Nullable<int> n_relnum { get; set; }
        public Nullable<int> n_rectime { get; set; }
        public Nullable<int> n_timetaken { get; set; }
        public Nullable<int> n_remotenum { get; set; }
        public Nullable<int> n_remoteflags { get; set; }
        public Nullable<int> n_storenum { get; set; }
        public Nullable<int> n_cardstage { get; set; }
        public string str_authcode { get; set; }
        public Nullable<int> n_contactid { get; set; }
        public Nullable<int> n_addressid { get; set; }
        public Nullable<int> n_nameid { get; set; }
        public Nullable<System.DateTime> tstamp { get; set; }
        public Nullable<int> n_delcharge { get; set; }
        public Nullable<int> n_flags { get; set; }
        public Nullable<int> n_cardcharge { get; set; }
        public Nullable<int> n_ordercost { get; set; }
        public Nullable<int> n_orderpoints { get; set; }
        public Nullable<int> n_delcomm { get; set; }
        public Nullable<int> n_distance { get; set; }
        public Nullable<int> n_priceadjust { get; set; }
        public Nullable<int> n_webstatus { get; set; }
        public string str_reason { get; set; }
        public Nullable<System.DateTime> n_orderoriginallyplacedtime { get; set; }
        public string str_datacashid { get; set; }
        public Nullable<int> n_tillid { get; set; }
        public Nullable<int> n_covers { get; set; }
        public Nullable<int> n_ccflags { get; set; }
        public Nullable<int> n_opd { get; set; }
        public string str_contact { get; set; }
        public string str_name { get; set; }
        public Nullable<System.DateTime> entrydate { get; set; }
        public Nullable<System.DateTime> editdate { get; set; }
        public string username { get; set; }
        public string machine { get; set; }
        public Nullable<int> n_totalmenuprice { get; set; }
        public Nullable<double> delchargetax { get; set; }
    }
}
