//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.DailyReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class scheduling
    {
        public System.Guid recordid { get; set; }
        public int autoid { get; set; }
        public int nstoreid { get; set; }
        public string str_payrollno { get; set; }
        public string str_employeename { get; set; }
        public Nullable<System.DateTime> d_start { get; set; }
        public Nullable<System.DateTime> d_end { get; set; }
        public Nullable<short> n_type { get; set; }
        public System.DateTime thedate { get; set; }
        public Nullable<short> n_shifttype { get; set; }
        public Nullable<int> n_payrate { get; set; }
        public Nullable<int> n_minspaid { get; set; }
        public Nullable<int> n_delcom { get; set; }
        public string str_notes { get; set; }
        public System.DateTime entrydate { get; set; }
    }
}
