//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.DailyReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class store
    {
        public System.Guid recordid { get; set; }
        public int autoid { get; set; }
        public int nstoreid { get; set; }
        public string strstorename { get; set; }
        public string strstaticip { get; set; }
        public string strserverip { get; set; }
        public Nullable<int> groupid { get; set; }
        public string lastupdate { get; set; }
        public string ftpid { get; set; }
        public string ftpuser { get; set; }
        public string ftppass { get; set; }
        public string storetype { get; set; }
        public string compstore { get; set; }
        public Nullable<int> menuid { get; set; }
        public Nullable<int> group1 { get; set; }
        public Nullable<int> group2 { get; set; }
        public Nullable<int> group3 { get; set; }
        public Nullable<int> group4 { get; set; }
        public Nullable<int> group5 { get; set; }
        public Nullable<int> group6 { get; set; }
        public Nullable<int> group7 { get; set; }
        public string companyid { get; set; }
        public string vtid { get; set; }
        public string accno { get; set; }
        public string sortcode { get; set; }
        public string accname { get; set; }
        public string franchisee { get; set; }
        public Nullable<int> menuversion { get; set; }
        public Nullable<System.DateTime> menuupdate { get; set; }
        public System.DateTime entrydate { get; set; }
        public System.DateTime editdate { get; set; }
        public string username { get; set; }
        public string machine { get; set; }
        public string contactnumber { get; set; }
        public Nullable<int> countrykey { get; set; }
    }
}
