//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromedaDataAccessEntityFramework.Model.AndroAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.MyAndromedaUsers = new HashSet<MyAndromedaUser>();
            this.Stores = new HashSet<Store>();
        }
    
        public int Id { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> ChainId { get; set; }
        public int CountryId { get; set; }
    
        public virtual Chain Chain { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<MyAndromedaUser> MyAndromedaUsers { get; set; }
        public virtual ICollection<Store> Stores { get; set; }
    }
}
