//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.Model.AndroAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreOccasionTime
    {
        public System.Guid Id { get; set; }
        public int StoreId { get; set; }
        public System.DateTime EndUtc { get; set; }
        public string EndTimezone { get; set; }
        public bool IsAllDay { get; set; }
        public string RecurrenceException { get; set; }
        public string RecurrenceRule { get; set; }
        public System.DateTime StartUtc { get; set; }
        public string StartTimezone { get; set; }
        public string Occasions { get; set; }
        public string Title { get; set; }
        public Nullable<int> DataVersion { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
