//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroAdminDataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACSApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACSApplication()
        {
            this.ACSApplicationSites = new HashSet<ACSApplicationSite>();
            this.AndroWebOrderingWebsites = new HashSet<AndroWebOrderingWebsite>();
            this.HostV2 = new HashSet<HostV2>();
            this.Hosts = new HashSet<Host>();
        }
    
        public int Id { get; set; }
        public string ExternalApplicationId { get; set; }
        public string Name { get; set; }
        public string ExternalDisplayName { get; set; }
        public int PartnerId { get; set; }
        public int DataVersion { get; set; }
        public string WebHookSettings { get; set; }
        public Nullable<System.Guid> EnvironmentId { get; set; }
    
        public virtual ACSApplication ACSApplication1 { get; set; }
        public virtual ACSApplication ACSApplication2 { get; set; }
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACSApplicationSite> ACSApplicationSites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AndroWebOrderingWebsite> AndroWebOrderingWebsites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostV2> HostV2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Host> Hosts { get; set; }
        public virtual Environment Environment { get; set; }
    }
}
