//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromedaDataAccessEntityFramework.Model.MyAndromeda
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailCampaignAudit
    {
        public int Id { get; set; }
        public int EmailCampaignId { get; set; }
        public string EditedByUserName { get; set; }
        public System.DateTime ActionOn { get; set; }
        public string Message { get; set; }
    
        public virtual EmailCampaign EmailCampaign { get; set; }
    }
}
