//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromedaDataAccessEntityFramework.Model.MyAndromeda
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.EnrolmentLevels = new HashSet<EnrolmentLevel>();
            this.RolePermissions = new HashSet<RolePermissions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<EnrolmentLevel> EnrolmentLevels { get; set; }
        public virtual ICollection<RolePermissions> RolePermissions { get; set; }
    }
}
