//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.Model.MyAndromeda
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingContact
    {
        public int AndromedaSiteId { get; set; }
        public string Name { get; set; }
        public string From { get; set; }
        public string ReplyTo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string PostCode { get; set; }
        public string Country { get; set; }
    }
}
