//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.Model.MyAndromeda
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiteMenu()
        {
            this.MenuItems = new HashSet<MenuItem>();
            this.SiteMenuPublishTaskHistories = new HashSet<SiteMenuPublishTaskHistory>();
        }
    
        public System.Guid Id { get; set; }
        public int AndromediaId { get; set; }
        public int DataVersion { get; set; }
        public Nullable<System.DateTime> LastUpdatedUtc { get; set; }
        public Nullable<int> SiteMenuMediaServerId { get; set; }
        public Nullable<int> SiteMenuMediaProfileId { get; set; }
        public Nullable<int> AccessMenuVersion { get; set; }
        public Nullable<int> SiteMenuFtpBackupDownloadTaskId { get; set; }
        public Nullable<int> SiteMenuFtpBackupUploadTaskId { get; set; }
        public Nullable<int> SiteMenuPublishTaskId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItem> MenuItems { get; set; }
        public virtual SiteMenuFtpBackupDownloadTask SiteMenuFtpBackupDownloadTask { get; set; }
        public virtual SiteMenuFtpBackupUploadTask SiteMenuFtpBackupUploadTask { get; set; }
        public virtual SiteMenuMediaProfile SiteMenuMediaProfile { get; set; }
        public virtual SiteMenuMediaServer SiteMenuMediaServer { get; set; }
        public virtual SiteMenuPublishTask SiteMenuPublishTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteMenuPublishTaskHistory> SiteMenuPublishTaskHistories { get; set; }
    }
}
