//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromedaDataAccessEntityFramework.Model.MyAndromeda
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailCampaignTask
    {
        public int Id { get; set; }
        public int EmailCampaignId { get; set; }
        public bool Started { get; set; }
        public bool Completed { get; set; }
        public int EmailCampaignSettingsId { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public Nullable<System.DateTime> RunLaterOnUtc { get; set; }
        public Nullable<System.DateTime> RanAtUtc { get; set; }
        public Nullable<System.DateTime> RetryAfter { get; set; }
        public bool Canceled { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
    
        public virtual EmailCampaign EmailCampaign { get; set; }
        public virtual EmailCampaignSetting EmailCampaignSetting { get; set; }
    }
}
