//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromedaDataAccessEntityFramework.Model.MyAndromeda
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserIpLock
    {
        public int UserId { get; set; }
        public bool Enabled { get; set; }
        public string ValidIpV4Ranges { get; set; }
    
        public virtual UserRecord UserRecord { get; set; }
    }
}
