//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace OrderTracking.ClientMap.ClientMapService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ExternalMapTrackingSoap", Namespace="http://OrderTracking.Androtechnology.co.uk")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entity))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class ExternalMapTracking : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetClientOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientOrderByCredentialsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPremisesDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStoreOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ExternalMapTracking() {
            this.Url = global::OrderTracking.ClientMap.Properties.Settings.Default.OrderTracking_ClientMap_ClientMapService_ExternalMapTracking;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetClientOrderCompletedEventHandler GetClientOrderCompleted;
        
        /// <remarks/>
        public event GetClientOrderByCredentialsCompletedEventHandler GetClientOrderByCredentialsCompleted;
        
        /// <remarks/>
        public event GetPremisesDataCompletedEventHandler GetPremisesDataCompleted;
        
        /// <remarks/>
        public event GetStoreCompletedEventHandler GetStoreCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://OrderTracking.Androtechnology.co.uk/GetClientOrder", RequestNamespace="http://OrderTracking.Androtechnology.co.uk", ResponseNamespace="http://OrderTracking.Androtechnology.co.uk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientMapData GetClientOrder(string userName, string password, string credentials) {
            object[] results = this.Invoke("GetClientOrder", new object[] {
                        userName,
                        password,
                        credentials});
            return ((ClientMapData)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientOrderAsync(string userName, string password, string credentials) {
            this.GetClientOrderAsync(userName, password, credentials, null);
        }
        
        /// <remarks/>
        public void GetClientOrderAsync(string userName, string password, string credentials, object userState) {
            if ((this.GetClientOrderOperationCompleted == null)) {
                this.GetClientOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientOrderOperationCompleted);
            }
            this.InvokeAsync("GetClientOrder", new object[] {
                        userName,
                        password,
                        credentials}, this.GetClientOrderOperationCompleted, userState);
        }
        
        private void OnGetClientOrderOperationCompleted(object arg) {
            if ((this.GetClientOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientOrderCompleted(this, new GetClientOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://OrderTracking.Androtechnology.co.uk/GetClientOrderByCredentials", RequestNamespace="http://OrderTracking.Androtechnology.co.uk", ResponseNamespace="http://OrderTracking.Androtechnology.co.uk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientMapData GetClientOrderByCredentials(string credentials) {
            object[] results = this.Invoke("GetClientOrderByCredentials", new object[] {
                        credentials});
            return ((ClientMapData)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientOrderByCredentialsAsync(string credentials) {
            this.GetClientOrderByCredentialsAsync(credentials, null);
        }
        
        /// <remarks/>
        public void GetClientOrderByCredentialsAsync(string credentials, object userState) {
            if ((this.GetClientOrderByCredentialsOperationCompleted == null)) {
                this.GetClientOrderByCredentialsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientOrderByCredentialsOperationCompleted);
            }
            this.InvokeAsync("GetClientOrderByCredentials", new object[] {
                        credentials}, this.GetClientOrderByCredentialsOperationCompleted, userState);
        }
        
        private void OnGetClientOrderByCredentialsOperationCompleted(object arg) {
            if ((this.GetClientOrderByCredentialsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientOrderByCredentialsCompleted(this, new GetClientOrderByCredentialsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://OrderTracking.Androtechnology.co.uk/GetPremisesData", RequestNamespace="http://OrderTracking.Androtechnology.co.uk", ResponseNamespace="http://OrderTracking.Androtechnology.co.uk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StoreMapData GetPremisesData(string userName, string password) {
            object[] results = this.Invoke("GetPremisesData", new object[] {
                        userName,
                        password});
            return ((StoreMapData)(results[0]));
        }
        
        /// <remarks/>
        public void GetPremisesDataAsync(string userName, string password) {
            this.GetPremisesDataAsync(userName, password, null);
        }
        
        /// <remarks/>
        public void GetPremisesDataAsync(string userName, string password, object userState) {
            if ((this.GetPremisesDataOperationCompleted == null)) {
                this.GetPremisesDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPremisesDataOperationCompleted);
            }
            this.InvokeAsync("GetPremisesData", new object[] {
                        userName,
                        password}, this.GetPremisesDataOperationCompleted, userState);
        }
        
        private void OnGetPremisesDataOperationCompleted(object arg) {
            if ((this.GetPremisesDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPremisesDataCompleted(this, new GetPremisesDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://OrderTracking.Androtechnology.co.uk/GetStore", RequestNamespace="http://OrderTracking.Androtechnology.co.uk", ResponseNamespace="http://OrderTracking.Androtechnology.co.uk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Store GetStore(string userName, string password) {
            object[] results = this.Invoke("GetStore", new object[] {
                        userName,
                        password});
            return ((Store)(results[0]));
        }
        
        /// <remarks/>
        public void GetStoreAsync(string userName, string password) {
            this.GetStoreAsync(userName, password, null);
        }
        
        /// <remarks/>
        public void GetStoreAsync(string userName, string password, object userState) {
            if ((this.GetStoreOperationCompleted == null)) {
                this.GetStoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStoreOperationCompleted);
            }
            this.InvokeAsync("GetStore", new object[] {
                        userName,
                        password}, this.GetStoreOperationCompleted, userState);
        }
        
        private void OnGetStoreOperationCompleted(object arg) {
            if ((this.GetStoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStoreCompleted(this, new GetStoreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderTracking.Androtechnology.co.uk")]
    public partial class ClientMapData {
        
        private DeliveryCustomer customerField;
        
        private DeliveryOrder deliveryOrderField;
        
        private DeliveryPremises premisesField;
        
        private DeliveryDriver deliveryDriverField;
        
        private string orderStatusField;
        
        private string orderStatusTimeField;
        
        private string orderProcessorField;
        
        /// <remarks/>
        public DeliveryCustomer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public DeliveryOrder DeliveryOrder {
            get {
                return this.deliveryOrderField;
            }
            set {
                this.deliveryOrderField = value;
            }
        }
        
        /// <remarks/>
        public DeliveryPremises Premises {
            get {
                return this.premisesField;
            }
            set {
                this.premisesField = value;
            }
        }
        
        /// <remarks/>
        public DeliveryDriver DeliveryDriver {
            get {
                return this.deliveryDriverField;
            }
            set {
                this.deliveryDriverField = value;
            }
        }
        
        /// <remarks/>
        public string OrderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
            }
        }
        
        /// <remarks/>
        public string OrderStatusTime {
            get {
                return this.orderStatusTimeField;
            }
            set {
                this.orderStatusTimeField = value;
            }
        }
        
        /// <remarks/>
        public string OrderProcessor {
            get {
                return this.orderProcessorField;
            }
            set {
                this.orderProcessorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderTracking.Androtechnology.co.uk")]
    public partial class DeliveryCustomer {
        
        private string nameField;
        
        private string credentialsField;
        
        private float longitudeField;
        
        private float latitudeField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
            }
        }
        
        /// <remarks/>
        public float Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public float Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Coordinates))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Store))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderTracking.Androtechnology.co.uk")]
    public abstract partial class Entity {
        
        private System.Nullable<long> idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderTracking.Androtechnology.co.uk")]
    public partial class Coordinates : Entity {
        
        private float longitudeField;
        
        private float latitudeField;
        
        /// <remarks/>
        public float Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public float Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderTracking.Androtechnology.co.uk")]
    public partial class Store : Entity {
        
        private object[] driversField;
        
        private object[] ordersField;
        
        private object[] trackersField;
        
        private string externalStoreIdField;
        
        private string nameField;
        
        private short deliveryRadiusField;
        
        private Coordinates coordinatesField;
        
        /// <remarks/>
        public object[] Drivers {
            get {
                return this.driversField;
            }
            set {
                this.driversField = value;
            }
        }
        
        /// <remarks/>
        public object[] Orders {
            get {
                return this.ordersField;
            }
            set {
                this.ordersField = value;
            }
        }
        
        /// <remarks/>
        public object[] Trackers {
            get {
                return this.trackersField;
            }
            set {
                this.trackersField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalStoreId {
            get {
                return this.externalStoreIdField;
            }
            set {
                this.externalStoreIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public short DeliveryRadius {
            get {
                return this.deliveryRadiusField;
            }
            set {
                this.deliveryRadiusField = value;
            }
        }
        
        /// <remarks/>
        public Coordinates Coordinates {
            get {
                return this.coordinatesField;
            }
            set {
                this.coordinatesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderTracking.Androtechnology.co.uk")]
    public partial class Delivery {
        
        private bool proximityDeliveredField;
        
        private string externalIdField;
        
        private long statusIdField;
        
        /// <remarks/>
        public bool ProximityDelivered {
            get {
                return this.proximityDeliveredField;
            }
            set {
                this.proximityDeliveredField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        public long StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderTracking.Androtechnology.co.uk")]
    public partial class PremisesDriver {
        
        private string idField;
        
        private string externalIdField;
        
        private bool hasFixField;
        
        private int batteryLevelField;
        
        private Delivery[] deliveriesField;
        
        private float longitudeField;
        
        private float latitudeField;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ExternalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        public bool HasFix {
            get {
                return this.hasFixField;
            }
            set {
                this.hasFixField = value;
            }
        }
        
        /// <remarks/>
        public int BatteryLevel {
            get {
                return this.batteryLevelField;
            }
            set {
                this.batteryLevelField = value;
            }
        }
        
        /// <remarks/>
        public Delivery[] Deliveries {
            get {
                return this.deliveriesField;
            }
            set {
                this.deliveriesField = value;
            }
        }
        
        /// <remarks/>
        public float Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public float Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderTracking.Androtechnology.co.uk")]
    public partial class StoreMapData {
        
        private PremisesDriver[] premisesDriversField;
        
        private Delivery[] outStandingDeliveriesField;
        
        /// <remarks/>
        public PremisesDriver[] PremisesDrivers {
            get {
                return this.premisesDriversField;
            }
            set {
                this.premisesDriversField = value;
            }
        }
        
        /// <remarks/>
        public Delivery[] OutStandingDeliveries {
            get {
                return this.outStandingDeliveriesField;
            }
            set {
                this.outStandingDeliveriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderTracking.Androtechnology.co.uk")]
    public partial class DeliveryDriver {
        
        private bool hasFixField;
        
        private float longitudeField;
        
        private float latitudeField;
        
        /// <remarks/>
        public bool HasFix {
            get {
                return this.hasFixField;
            }
            set {
                this.hasFixField = value;
            }
        }
        
        /// <remarks/>
        public float Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public float Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderTracking.Androtechnology.co.uk")]
    public partial class DeliveryPremises {
        
        private string externalStoreIdField;
        
        private string nameField;
        
        private float longitudeField;
        
        private float latitudeField;
        
        /// <remarks/>
        public string ExternalStoreId {
            get {
                return this.externalStoreIdField;
            }
            set {
                this.externalStoreIdField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public float Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public float Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderTracking.Androtechnology.co.uk")]
    public partial class DeliveryOrder {
        
        private bool proximityDeliveredField;
        
        private string[] itemsField;
        
        /// <remarks/>
        public bool ProximityDelivered {
            get {
                return this.proximityDeliveredField;
            }
            set {
                this.proximityDeliveredField = value;
            }
        }
        
        /// <remarks/>
        public string[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetClientOrderCompletedEventHandler(object sender, GetClientOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientMapData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientMapData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetClientOrderByCredentialsCompletedEventHandler(object sender, GetClientOrderByCredentialsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientOrderByCredentialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientOrderByCredentialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientMapData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientMapData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetPremisesDataCompletedEventHandler(object sender, GetPremisesDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPremisesDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPremisesDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StoreMapData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StoreMapData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetStoreCompletedEventHandler(object sender, GetStoreCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Store Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Store)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591