//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroAdminDataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_AMS_upload
    {
        public int id { get; set; }
        public Nullable<System.DateTime> LastBusinessDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
