//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroAdminDataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreMenuThumbnail
    {
        public int Id { get; set; }
        public int StoreId { get; set; }
        public int Version { get; set; }
        public string XmlMenuThumbnailData { get; set; }
        public string JsonMenuThumbnailsData { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
