//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroAdminDataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreDevice
    {
        public System.Guid Id { get; set; }
        public int StoreId { get; set; }
        public System.Guid DeviceId { get; set; }
        public string Parameters { get; set; }
        public int DataVersion { get; set; }
        public bool Removed { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Store Store { get; set; }
    }
}
