//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.Model.MyAndromeda
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItem()
        {
            this.MenuItemThumbnails = new HashSet<MenuItemThumbnail>();
        }
    
        public System.Guid Id { get; set; }
        public int ItemId { get; set; }
        public string Name { get; set; }
        public string WebName { get; set; }
        public string WebDescription { get; set; }
        public System.Guid SiteMenuId { get; set; }
        public bool Enabled { get; set; }
    
        public virtual SiteMenu SiteMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItemThumbnail> MenuItemThumbnails { get; set; }
    }
}
