//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.Model.MyAndromeda
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMenuMediaProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiteMenuMediaProfile()
        {
            this.SiteMenus = new HashSet<SiteMenu>();
            this.SiteMenuMediaProfileSizes = new HashSet<SiteMenuMediaProfileSize>();
        }
    
        public int Id { get; set; }
        public string Mode { get; set; }
        public string Alignment { get; set; }
        public string PaddingColour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteMenu> SiteMenus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteMenuMediaProfileSize> SiteMenuMediaProfileSizes { get; set; }
    }
}
