//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouseDataAccessEntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderPayment()
        {
            this.OrderPaymentPSPs = new HashSet<OrderPaymentPSP>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid OrderHeaderID { get; set; }
        public string PaymentType { get; set; }
        public int Value { get; set; }
        public string AuthCode { get; set; }
        public string CVVStatus { get; set; }
        public string PayTypeName { get; set; }
        public string LastFourDigits { get; set; }
        public string PayProcessor { get; set; }
        public Nullable<int> PaymentCharge { get; set; }
    
        public virtual OrderHeader OrderHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPaymentPSP> OrderPaymentPSPs { get; set; }
    }
}
