//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignpostDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACSApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACSApplication()
        {
            this.ACSApplicationSites = new HashSet<ACSApplicationSite>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.Guid EnvironmentId { get; set; }
        public string ExternalApplicationId { get; set; }
    
        public virtual Environment Environment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACSApplicationSite> ACSApplicationSites { get; set; }
    }
}
