//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignpostDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.LegacyHosts = new HashSet<LegacyHost>();
            this.LegacyHosts1 = new HashSet<LegacyHost>();
            this.LegacyHosts2 = new HashSet<LegacyHost>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public System.Guid EnvironmentId { get; set; }
        public System.Guid ServiceTypeId { get; set; }
        public int Order { get; set; }
        public int Version { get; set; }
    
        public virtual Environment Environment { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegacyHost> LegacyHosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegacyHost> LegacyHosts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegacyHost> LegacyHosts2 { get; set; }
    }
}
