//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.DailyReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySummary
    {
        public int RecordID { get; set; }
        public Nullable<System.DateTime> TheDate { get; set; }
        public Nullable<int> nIdealCOS { get; set; }
        public Nullable<int> nStoreID { get; set; }
        public Nullable<int> nCOLHourlyPay { get; set; }
        public Nullable<int> TotPay { get; set; }
        public Nullable<int> nWastage { get; set; }
        public Nullable<int> nInvDaily { get; set; }
        public Nullable<int> nInvWeekly { get; set; }
        public Nullable<int> nInvMonthly { get; set; }
        public Nullable<int> nDealsRec { get; set; }
        public Nullable<int> nTransIn { get; set; }
        public Nullable<int> nTransOut { get; set; }
        public Nullable<int> NetSales { get; set; }
        public Nullable<int> TotalOrders { get; set; }
        public Nullable<int> DineInNetSales { get; set; }
        public Nullable<int> DelNetSales { get; set; }
        public Nullable<int> CarryOutNetSales { get; set; }
        public Nullable<int> DineInTotalOrders { get; set; }
        public Nullable<int> DelTotalOrders { get; set; }
        public Nullable<int> CarryOutTotalOrders { get; set; }
        public Nullable<int> TotSalesTax { get; set; }
        public Nullable<int> ManagerDiscounts { get; set; }
        public Nullable<int> DealDiscounts { get; set; }
        public Nullable<int> FullMenuPrice { get; set; }
        public Nullable<int> LabourSeconds { get; set; }
        public Nullable<int> LabourCost { get; set; }
        public Nullable<int> TotalCancels { get; set; }
        public Nullable<int> valueCancels { get; set; }
        public Nullable<int> nCloseDailyCount { get; set; }
        public Nullable<int> nCloseWeeklyCount { get; set; }
        public Nullable<int> nCloseMonthlyCount { get; set; }
        public Nullable<int> NumOrdersLT30Mins { get; set; }
        public Nullable<int> NumOrdersLT45Mins { get; set; }
        public Nullable<int> AvgMake { get; set; }
        public Nullable<int> AvgOutTheDoor { get; set; }
        public Nullable<int> AvgDoorTime { get; set; }
        public Nullable<int> TotCOS { get; set; }
        public Nullable<double> nReceipt { get; set; }
        public Nullable<int> BottleDeposit { get; set; }
        public Nullable<int> AltBottleDeposit { get; set; }
        public Nullable<int> RefundsInCurr { get; set; }
        public Nullable<int> RefundsQty { get; set; }
        public Nullable<int> OnlineNetSales { get; set; }
        public Nullable<int> OnlineGrossSales { get; set; }
        public Nullable<int> OnlineDelNetSales { get; set; }
        public Nullable<int> OnlineColNetSales { get; set; }
        public Nullable<int> OnlineDelGrossSales { get; set; }
        public Nullable<int> OnlineColGrossSales { get; set; }
        public Nullable<int> OnlineTrans { get; set; }
        public Nullable<int> OnlineDelTrans { get; set; }
        public Nullable<int> OnlineColTrans { get; set; }
        public Nullable<int> OnlineTotalTax { get; set; }
        public Nullable<int> OnlineDelTax { get; set; }
        public Nullable<int> OnlineColTax { get; set; }
        public Nullable<System.DateTime> Create_TimeStamp { get; set; }
        public Nullable<System.DateTime> Update_TimeStamp { get; set; }
        public string nCustomerID { get; set; }
        public Nullable<int> RackTime { get; set; }
    }
}
