//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromedaDataAccessEntityFramework.Model.AndroAdminUsers
{
    using System;
    using System.Collections.Generic;
    
    public partial class AndroUserPermission
    {
        public int id { get; set; }
        public int AndroUser { get; set; }
        public int Project { get; set; }
    
        public virtual AndroUser tbl_AndroUser { get; set; }
        public virtual Project tbl_Project { get; set; }
    }
}
