//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroCloudDataAccessEntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMenu
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> SiteID { get; set; }
        public Nullable<int> Version { get; set; }
        public string MenuType { get; set; }
        public string menuData { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string menuDataThumbnails { get; set; }
        public string MenuDataThumbnailsVersion { get; set; }
        public string MenuDataExtended { get; set; }
        public string MenuDataExtendedVersion { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
