//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.DataWarehouse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataWarehouseDbContext : DbContext
    {
        public DataWarehouseDbContext()
            : base("name=DataWarehouseDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ContactType> ContactTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerAccount> CustomerAccounts { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<MarketingLevel> MarketingLevels { get; set; }
        public virtual DbSet<OrderLine> OrderLines { get; set; }
        public virtual DbSet<OrderStatu> OrderStatus { get; set; }
        public virtual DbSet<OrderStatusHistory> OrderStatusHistories { get; set; }
        public virtual DbSet<modifier> modifiers { get; set; }
        public virtual DbSet<SiteVoucher> SiteVouchers { get; set; }
        public virtual DbSet<UsedVoucher> UsedVouchers { get; set; }
        public virtual DbSet<Voucher> Vouchers { get; set; }
        public virtual DbSet<ACSErrorCode> ACSErrorCodes { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<PasswordResetRequest> PasswordResetRequests { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CustomerLoyalty> CustomerLoyalties { get; set; }
        public virtual DbSet<AndroWebTelemetry> AndroWebTelemetries { get; set; }
        public virtual DbSet<AndroWebTelemetrySession> AndroWebTelemetrySessions { get; set; }
        public virtual DbSet<CustomerFeedback> CustomerFeedbacks { get; set; }
        public virtual DbSet<CustomerFeedbackCategory> CustomerFeedbackCategories { get; set; }
        public virtual DbSet<OrderDiscount> OrderDiscounts { get; set; }
        public virtual DbSet<OrderDiscountType> OrderDiscountTypes { get; set; }
        public virtual DbSet<OrderLoyalty> OrderLoyalties { get; set; }
        public virtual DbSet<OrderPaymentPSP> OrderPaymentPSPs { get; set; }
        public virtual DbSet<OrderPayment> OrderPayments { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<EmailCategory> EmailCategories { get; set; }
        public virtual DbSet<EmailHistory> EmailHistories { get; set; }
        public virtual DbSet<OrderHeader> OrderHeaders { get; set; }
        public virtual DbSet<IbsOrder> IbsOrders { get; set; }
        public virtual DbSet<IbsRamesesTranslation> IbsRamesesTranslations { get; set; }
        public virtual DbSet<IbsPaymentTypeTranslation> IbsPaymentTypeTranslations { get; set; }
        public virtual DbSet<EmployeeStoreLinkRecord> EmployeeStoreLinkRecords { get; set; }
        public virtual DbSet<EmployeeRecord> EmployeeRecords { get; set; }
    }
}
