//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.DailyReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public System.Guid recordid { get; set; }
        public int autoid { get; set; }
        public Nullable<int> nstoreid { get; set; }
        public Nullable<int> n_id { get; set; }
        public string org1 { get; set; }
        public string org2 { get; set; }
        public string org3 { get; set; }
        public string prem1 { get; set; }
        public string prem2 { get; set; }
        public string prem3 { get; set; }
        public string roadnum { get; set; }
        public string roadname { get; set; }
        public string userlocality { get; set; }
        public string locality { get; set; }
        public string town { get; set; }
        public string county { get; set; }
        public string postcode { get; set; }
        public string country { get; set; }
        public string grid { get; set; }
        public string refno { get; set; }
        public string str_directions { get; set; }
        public string str_staffnotes { get; set; }
        public string str_dps { get; set; }
        public string str_type { get; set; }
        public Nullable<int> n_flags { get; set; }
        public Nullable<int> n_timesordered { get; set; }
        public Nullable<System.DateTime> tstamp { get; set; }
        public Nullable<System.DateTime> dtfirstorder { get; set; }
        public Nullable<System.DateTime> dtlastorder { get; set; }
        public System.DateTime entrydate { get; set; }
        public System.DateTime editdate { get; set; }
        public string username { get; set; }
        public string machine { get; set; }
        public Nullable<int> nDistance { get; set; }
        public string Prem4 { get; set; }
        public string Prem5 { get; set; }
        public string Prem6 { get; set; }
        public string SubLocality { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string SubRoad { get; set; }
        public Nullable<bool> userdef1 { get; set; }
    }
}
