//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.DailyReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HourlyServiceMetric
    {
        public int nStoreID { get; set; }
        public int thehour { get; set; }
        public System.DateTime thedate { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public Nullable<double> OrderNet { get; set; }
        public Nullable<double> OrderVAT { get; set; }
        public Nullable<double> UnDiscounted { get; set; }
        public Nullable<double> OrderDiscount { get; set; }
        public Nullable<double> OrderGross { get; set; }
        public Nullable<int> DeliveryCount { get; set; }
        public Nullable<int> CollectionCount { get; set; }
        public Nullable<int> DineInCount { get; set; }
        public Nullable<int> DriveThruCount { get; set; }
        public Nullable<int> TotalOrders { get; set; }
        public Nullable<double> FMPOrder { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> OrderPriceNet { get; set; }
        public Nullable<double> nAvgDoor { get; set; }
        public Nullable<double> nAvgInstore { get; set; }
        public Nullable<double> nAvgRackTime { get; set; }
        public Nullable<double> nAvgDrive { get; set; }
        public Nullable<int> LessThen15 { get; set; }
        public Nullable<int> Over15lessThan20 { get; set; }
        public Nullable<int> Over20lessThan25 { get; set; }
        public Nullable<int> Over25lessThan30 { get; set; }
        public Nullable<int> Over30lessThan35 { get; set; }
        public Nullable<int> Over35lessThan45 { get; set; }
        public Nullable<int> Over45lessThan60 { get; set; }
        public Nullable<int> Over60 { get; set; }
    }
}
