//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.DailyReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class primarycat
    {
        public Nullable<System.Guid> recordid { get; set; }
        public int autoid { get; set; }
        public Nullable<int> nstoreid { get; set; }
        public Nullable<int> nuid { get; set; }
        public Nullable<int> nmenubarid { get; set; }
        public string strname { get; set; }
        public Nullable<int> ntimesavailable { get; set; }
        public Nullable<int> noccasions { get; set; }
        public Nullable<int> nflags { get; set; }
        public Nullable<int> nicon { get; set; }
        public Nullable<int> ncompanyid { get; set; }
    }
}
