//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouseDataAccessEntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.SiteVouchers = new HashSet<SiteVoucher>();
            this.UsedVouchers = new HashSet<UsedVoucher>();
        }
    
        public System.Guid Id { get; set; }
        public bool Active { get; set; }
        public string VoucherCode { get; set; }
        public string Description { get; set; }
        public string Occasion { get; set; }
        public Nullable<decimal> MinimumOrderAmount { get; set; }
        public Nullable<int> MaxRepetitions { get; set; }
        public bool Combinable { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDataTime { get; set; }
        public string AvailableOnDays { get; set; }
        public Nullable<System.TimeSpan> StartTimeOfDayAvailable { get; set; }
        public Nullable<System.TimeSpan> EndTimeOfDayAvailable { get; set; }
        public string DiscountType { get; set; }
        public decimal DiscountValue { get; set; }
        public bool Removed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteVoucher> SiteVouchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsedVoucher> UsedVouchers { get; set; }
    }
}
