//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouseDataAccessEntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDiscount
    {
        public System.Guid ID { get; set; }
        public System.Guid OrderHeaderId { get; set; }
        public string Type { get; set; }
        public string DiscountType { get; set; }
        public int DiscountTypeAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public string InitialDiscountReason { get; set; }
    
        public virtual OrderDiscountType OrderDiscountType { get; set; }
        public virtual OrderHeader OrderHeader { get; set; }
    }
}
