//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Master {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Master() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Master", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        internal static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Chain.
        /// </summary>
        internal static string AddNewChain {
            get {
                return ResourceManager.GetString("AddNewChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Store.
        /// </summary>
        internal static string AddNewStore {
            get {
                return ResourceManager.GetString("AddNewStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add store/s.
        /// </summary>
        internal static string AddStores {
            get {
                return ResourceManager.GetString("AddStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes.
        /// </summary>
        internal static string ApplyChanges {
            get {
                return ResourceManager.GetString("ApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Level.
        /// </summary>
        internal static string BatteryLevel {
            get {
                return ResourceManager.GetString("BatteryLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Name.
        /// </summary>
        internal static string BuildingName {
            get {
                return ResourceManager.GetString("BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain Name.
        /// </summary>
        internal static string ChainName {
            get {
                return ResourceManager.GetString("ChainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chains.
        /// </summary>
        internal static string Chains {
            get {
                return ResourceManager.GetString("Chains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Logs.
        /// </summary>
        internal static string ClearAllLogs {
            get {
                return ResourceManager.GetString("ClearAllLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Monitor.
        /// </summary>
        internal static string ClearMonitor {
            get {
                return ResourceManager.GetString("ClearMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        internal static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Details.
        /// </summary>
        internal static string CurrentDetails {
            get {
                return ResourceManager.GetString("CurrentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizable.
        /// </summary>
        internal static string Customizable {
            get {
                return ResourceManager.GetString("Customizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom value.
        /// </summary>
        internal static string CustomValue {
            get {
                return ResourceManager.GetString("CustomValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Radius.
        /// </summary>
        internal static string DeliveryRadius {
            get {
                return ResourceManager.GetString("DeliveryRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers.
        /// </summary>
        internal static string Drivers {
            get {
                return ResourceManager.GetString("Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit website.
        /// </summary>
        internal static string EditWebsite {
            get {
                return ResourceManager.GetString("EditWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Driver Id.
        /// </summary>
        internal static string ExternalDriverId {
            get {
                return ResourceManager.GetString("ExternalDriverId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate chain web site.
        /// </summary>
        internal static string GenerateSite {
            get {
                return ResourceManager.GetString("GenerateSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Logs.
        /// </summary>
        internal static string GlobalLogs {
            get {
                return ResourceManager.GetString("GlobalLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Disabled.
        /// </summary>
        internal static string GPSDisabled {
            get {
                return ResourceManager.GetString("GPSDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Enabled.
        /// </summary>
        internal static string GPSEnabled {
            get {
                return ResourceManager.GetString("GPSEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Website.
        /// </summary>
        internal static string NoWebSite {
            get {
                return ResourceManager.GetString("NoWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Items.
        /// </summary>
        internal static string OrderItems {
            get {
                return ResourceManager.GetString("OrderItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Taken.
        /// </summary>
        internal static string OrdersTaken {
            get {
                return ResourceManager.GetString("OrdersTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Weeks Logs.
        /// </summary>
        internal static string PastWeeksLogs {
            get {
                return ResourceManager.GetString("PastWeeksLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        internal static string PostCode {
            get {
                return ResourceManager.GetString("PostCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximity delivered.
        /// </summary>
        internal static string ProximityDelivered {
            get {
                return ResourceManager.GetString("ProximityDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rameses Store Id.
        /// </summary>
        internal static string RamesesStoreId {
            get {
                return ResourceManager.GetString("RamesesStoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected store/s.
        /// </summary>
        internal static string RemoveStores {
            get {
                return ResourceManager.GetString("RemoveStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Name.
        /// </summary>
        internal static string RoadName {
            get {
                return ResourceManager.GetString("RoadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Details.
        /// </summary>
        internal static string StoreDetails {
            get {
                return ResourceManager.GetString("StoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        internal static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        internal static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        internal static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Tracking.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todays Logs.
        /// </summary>
        internal static string TodaysLogs {
            get {
                return ResourceManager.GetString("TodaysLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackers.
        /// </summary>
        internal static string Trackers {
            get {
                return ResourceManager.GetString("Trackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker Status.
        /// </summary>
        internal static string TrackerStatus {
            get {
                return ResourceManager.GetString("TrackerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        internal static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All Stores.
        /// </summary>
        internal static string ViewAllStores {
            get {
                return ResourceManager.GetString("ViewAllStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Location.
        /// </summary>
        internal static string ViewLocation {
            get {
                return ResourceManager.GetString("ViewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Key.
        /// </summary>
        internal static string WebKey {
            get {
                return ResourceManager.GetString("WebKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Template.
        /// </summary>
        internal static string WebSiteTemplate {
            get {
                return ResourceManager.GetString("WebSiteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Changing the template will erase any website customization.  Selecting &quot;None&quot; will delete all website files and website customization for the chain..
        /// </summary>
        internal static string WebsiteTemplateWarning {
            get {
                return ResourceManager.GetString("WebsiteTemplateWarning", resourceCulture);
            }
        }
    }
}
