//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_PostCodes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OSPostCode
    {
        public string PostCode { get; set; }
        public string PostCodeNormalized { get; set; }
        public string Positional_quality_indicator { get; set; }
        public string Eastings { get; set; }
        public string Northings { get; set; }
        public string Country_code { get; set; }
        public string NHS_regional_HA_code { get; set; }
        public string NHS_HA_code { get; set; }
        public string Admin_county_code { get; set; }
        public string Admin_district_code { get; set; }
        public string Admin_ward_code { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
    }
}
