//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.DailyReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public System.Guid id { get; set; }
        public Nullable<int> nUID { get; set; }
        public string strName { get; set; }
        public Nullable<int> nType { get; set; }
        public Nullable<int> nDisplayFlags { get; set; }
        public Nullable<int> nCompanyId { get; set; }
        public Nullable<int> nHalfHalf { get; set; }
        public Nullable<int> w_menusectionId { get; set; }
        public string strWebTitle { get; set; }
        public Nullable<int> nToppingGroup1 { get; set; }
        public Nullable<int> nToppingGroup2 { get; set; }
        public Nullable<int> nToppingGroup3 { get; set; }
        public Nullable<int> nToppingGroup4 { get; set; }
        public Nullable<int> nToppingGroup5 { get; set; }
        public Nullable<int> nForeColor { get; set; }
        public Nullable<int> nBackColor { get; set; }
        public Nullable<int> nParentId { get; set; }
        public Nullable<int> nRecipeGroup { get; set; }
        public Nullable<int> nFlags { get; set; }
    }
}
