//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.DailyReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class menucontent
    {
        public int MenuContentsID { get; set; }
        public Nullable<int> nStoreID { get; set; }
        public Nullable<int> nMenuID { get; set; }
        public Nullable<int> nRecipeID { get; set; }
        public Nullable<int> nAmount { get; set; }
    }
}
