//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromeda.Data.DailyReporting.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class storegroup1
    {
        public System.Guid recordid { get; set; }
        public int autoid { get; set; }
        public int groupid { get; set; }
        public Nullable<int> groupposition { get; set; }
        public string groupcategory { get; set; }
        public string groupname { get; set; }
        public System.DateTime entrydate { get; set; }
        public System.DateTime editdate { get; set; }
        public string username { get; set; }
        public string machine { get; set; }
    }
}
