/*
    Copyright © 2014 Andromeda Trading Limited.  All rights reserved.
    THIS FILE AND ITS CONTENTS ARE PROTECTED BY COPYRIGHT AND/OR OTHER APPLICABLE LAW.
    ANY USE OF THE CONTENTS OF THIS FILE OR ANY PART OF THIS FILE WITHOUT EXPLICIT PERMISSION FROM ANDROMEDA TRADING LIMITED IS PROHIBITED.
*/
/* Text displayed on the web site */
var englishTextStrings = {
    dealsSection: 'Deals',
    noRestaurants: 'There are no restaurants',
    /* General */
    gExitWarning: 'WARNING: You\'ve currently got items in your basket.  If you continue your basket will be cleared.',
    /* Header */
    hPhone: 'Tel. ',
    hDeliveryAreaButton: 'Check if you\'re in our delivery area',
    hChangeStoreButton: 'Select a different store',
    hOrderNowButton: 'Menu',
    hHomeButon: 'Home',
    hStoreDetailsButon: 'Store details',
    hReturnToParentWebsiteButton: 'Return home',
    hSupportEmailPrompt: 'Email: ',
    hFeedbackButton: 'Feedback',
    hTwitter: '',
    hInstagram: '',
    hFacebook: '',
    hPinterest: '',
    /* Header: Site selector */
    hSiteSelectorPostcodePrompt: 'Lets check your postcode and see if we can deliver to you',
    hSiteSelectorPostcodeExample: 'e.g N5 2AB',
    hSiteSelectorPostcodeButton: 'GO',
    hSiteSelectorNoPostcode: 'Please enter a postcode',
    hBadDeliveryZone: 'Sorry, we don\'t deliver to your postcode',
    hShowAllRestaurants: 'Show all restaurants',
    hLoginPrompt: 'Login',
    hLoginButton: 'Sign in/Register',
    hForgetPasswordButton: 'Forgot your password?',
    hRegisterButton: 'Register',
    hMyProfileButton: 'MY PROFILE',
    hMyOrdersButton: 'MY ORDERS',
    hLogoutButton: 'LOGOUT',
    hUsernamePlaceholder: 'Username',
    hPasswordPlaceholder: 'Password',
    hLoggingIn: 'Logging in',
    hMissingEmail: 'Please enter an email address',
    hMissingPassword: 'Please enter a password',
    hUnableToLogin: 'Unable to login',
    hInvalidUserPass: 'Invalid username or password',
    hHelloLoggedIn: 'Hello {firstName}, you\'re ordering from {storeName}',
    hHelloNotLoggedIn: 'You\'re ordering from {storeName}',
    hHelloLoggedInNoStore: 'Hello {firstName}',
    /* Mobile header */
    hmLoginButton: 'Login',
    hmMyBasketButton: 'My basket',
    hmLoginRegisterButton: 'LOGIN/REGISTER',
    /* HOME */
    homeStoreDetailsTitle: 'Welcome to our Pizza Shop',
    homeStoreDetails: '',
    homeMenuTitle: 'Menu and Ordering',
    homeMenu: '',
    homeStoreDetailsButton: 'Learn More &gt;',
    homeMenuButton: 'Order online',
    /* SITE LIST */
    slChooseRestaurant: 'Please choose your local restaurant',
    slSorry: 'Sorry we do not deliver to your postcode!',
    slChangePostcodePrompt: 'For postcode ',
    slChangePostcodeButton: 'Change postcode',
    slSelectPostcodeButton: 'Or select a postcode for delivery',
    /* Password reset */
    prPasswordRetrieval: 'Password reset',
    prPasswordRetrievalInstructions: 'Please enter the email address you used when you registered.  We will send you an email containing instructions for how to reset your password.',
    prEmail: 'Email',
    prRetrievalPassword: 'Reset password',
    prCancel: 'Cancel',
    prEmailSent: 'We have sent you an email containing instructions for resetting your password',
    prGenericError: 'Sorry, there was a technical problem resetting your password',
    prNoEmail: 'Please enter your email address',
    prInvalidEmail: 'Please enter a valid email address',
    prNoPassword: 'Please enter your new password',
    prNoRepeatPassword: 'Please repeat your new password',
    prPasswordsDoNotMatch: 'Password and repated password do not match',
    prPassword: 'New password',
    prRepeatPassword: 'Re-enter new password',
    prPasswordToShort: 'Password must be at least 4 characters',
    prPasswordReset: 'Password reset',
    /* Register */
    lrLoginRegister: 'Login / register',
    lrLoginEmail: 'Email address',
    lrLoginPassword: 'Password',
    lrLoginButton: 'Login',
    lrWhoAreYou: 'Who are you?',
    lrFullName: "name",
    lrFirstName: 'First name',
    lrFirstNameEgP: 'e.g. Jack',
    lrSurname: 'Surname',
    lrSurnameEgP: 'e.g. Smith',
    lrEmailEgP: 'e.g. jack.smith@example.com',
    lrPassword: 'Password',
    lrReenterPassword: 'Re-enter password',
    lrPhoneNumber: 'phone number',
    lrPhoneNumberEgP: 'e.g. 0123 456789',
    lrRegisterMarketingInterests: 'Keep me updated about new products and special offers via',
    lrEmail: 'email',
    lrSms: "SMS",
    lrEmailMarketting: 'Let me know about new products and special offers',
    lrSMSMarketting: 'Let me know about new products and special offers',
    lrCreateAccountAddress: 'Where do you want your orders delivered to?',
    lrRegisterButton: 'Register',
    lrCancelButton: 'Cancel',
    lrMissingPassword: 'Please enter a password',
    lrMissingReneterPassword: 'Please re-enter the password',
    lrPasswordsDontMatch: 'The two passwords do not match',
    lrPasswordTooShort: 'Password must be at least 4 characters',
    lrMissingFirstName: "Please enter your first name",
    lrMissingSurname: "Please enter your surname",
    lrMissingEmail: "Please enter your email address",
    lrEmailNotValid: "Please enter a valid email address",
    lrPhoneMissing: "Please enter your phone number",
    lrMissingAddress1: "Address line 1 is required",
    lrMissingAddress2: "Address line 2 is required",
    lrMissingRoadName: "Please enter your road name",
    lrMissingTown: 'Please enter your town',
    lrPasswordMismatch: 'Passwords do not match',
    lrPassToShort: 'Password must be at least 4 characters',
    lrRegistering: 'Creating your account',
    lrEmailAlreadyUsed: 'An account already exists for this email address.  You can reset your password on the sign in page.',
    lrFacebookAlreadyUsed: 'An account already exists for this email address.  Please login using your email address and password.',
    lrUnableToCreateAccount: 'Unable to create account',
    lrMissingPostcode: 'Please enter your postcode',
    lrInvalidPostcode: 'Please enter a valid postcode',
    lrInvalidPhoneNumber: 'Please enter valid phone number',
    lrInvalidPhoneNumberMaxLength: 'Please enter valid phone number (Maximum Allowed: upto 15 digits)',
    /* My Profile */
    mpMyProfile: 'My profile',
    mpWhoAreYou: 'Who are you?',
    mpChangePassword: 'Change password',
    mpCurrentPassword: 'current password',
    mpNewPassword: 'password',
    mpConfirmNewPassword: 'confirm password',
    mpMyOrders: 'My orders',
    mpLogout: 'Logout',
    mpBackToMenu: 'Back to menu',
    mpSaveChangesButton: 'Save changes',
    mpMissingPasswords: 'If you want to change your password please enter you current password and the new passsword twice',
    mpWrongCurrentPassword: 'Wrong password',
    mpUnableToCreateAccount: 'Unable to save account changes',
    mpUpdatingUserProfile: 'Please wait ... updating user profile',
    /* Order history */
    moQuantity: 'Quantity',
    moPrice: 'Price',
    moOrderTotal: 'Order total',
    moRepeatOrder: 'Repeat order',
    moError: 'Sorry, unable to retrieve your orders',
    moNoOrders: 'You have not placed any orders',
    moPleaseWaitOrders: 'Please wait ... getting orders',
    moPleaseWaitOrder: 'Please wait ... getting order',
    moStatus0: 'received by store',
    moStatus1: 'received by store',
    moStatus2: 'in oven',
    moStatus3: 'ready for dispatch',
    moStatus4: 'out for delivery',
    moStatus5: 'completed',
    moStatus6: 'cancelled',
    /* Repeat order */
    roRepeatOrder: 'Repeat order',
    roDiscontinued: 'Sorry, this product has been discontinued',
    roOrderTotal: 'Order total',
    roAddToCart: 'Add items to my basket',
    roBack: 'Back to my profile',
    roOrderTotalPrompt: 'Order total',
    /* Menu */
    mMenuSections: 'Menu',
    /* Cart sidebar */
    sMyOrder: 'Order Summary',
    sDeliverToDoor: 'Deliver to door',
    sCollectFromStore: 'Collect from store',
    sModifyOrder: 'Modify Order',
    sReturnToCheckout: 'Return to checkout',
    sOffline: 'This store is not currently taking online orders.<br /><br />Please check back later or order directly from the store.',
    sEmpty1: 'There are no items in your order',
    sEmpty2: '',
    sItemCount1: 'There are ',
    sItemCount2: ' item/s in your order',
    sDiscountsPrompt: 'Discounts',
    sSubTotal: 'Subtotal:',
    sOrderTotal: 'Total Due:',
    sInvalid: 'One or more item in your order is not valid and will be automatically removed on checkout',
    sClear: 'Remove all',
    sCheckout: 'Checkout',
    sBackToMenu: 'Back to Menu',
    sRemove: 'Click an item to modify or remove it',
    sMinimumDelivOrder: 'Minimum delivery order ',
    sStoreClosed: 'Sorry, the store is closed',
    sRemovedDeliverySlots: 'One or more delivery time slots has been removed due to time restricted items in your cart',
    sRemovedCollectionSlots: 'One or more collection time slots has been removed due to time restricted items in your cart',
    /* Image view */
    ivClose: 'Click/tap on the image to hide it',
    /* Menu item (Menu) */
    miQuantity: 'Quantity',
    miAdd: 'Add',
    miCustomize: 'Customize',
    miNotAvailableAllDay: 'This item is not available today',
    miNotAvailableForHours: 'This item is only available from {hours}',
    miTemporarilyUnavailable: 'Sorry, this item is currently unavailable',
    miNotAvailableForCollection: 'Sorry, this item is not available for collection',
    miNotAvailableForDelivery: 'Sorry, this item is not available for delivery',
    /* Deals (Menu) */
    dAdd: 'Add',
    dCollectOnly: 'Collect from store only',
    dDeliverOnly: 'Deliver to door only',
    dNotToday: 'This deal is not available today',
    dMinSpend: 'Minimum spend ',
    /* Please wait */
    pwOneMomentPlease: 'One moment please',
    /* Store selector */
    ssStoreSelector: 'The following restaurants deliver to your postcode',
    //ssOrderFoodNow: 'Order food now', ?? not needed?
    ssShowMeAllTheRestaurants: 'Show me all the restaurants',
    ssCollect: 'You can also collect from the following restaurants',
    /* Store selector */
    sselStoreSelector: 'Store selector',
    /* Store details page */
    storeDetailsDeliveryTimes: 'We deliver at the following times',
    storeDetailsMonday: 'Monday:',
    storeDetailsTuesday: 'Tuesday:',
    storeDetailsWednesday: 'Wednesday:',
    storeDetailsThursday: 'Thursday:',
    storeDetailsFriday: 'Friday:',
    storeDetailsSaturday: 'Saturday:',
    storeDetailsSunday: 'Sunday:',
    /* Cart item */
    ciCollectOnly: 'Collect from store only',
    ciDeliverOnly: 'Deliver to door only',
    /* Disabled cart item */
    dciCollectOnly: 'Collect from store only',
    dciDeliverOnly: 'Deliver to door only',
    /* Cart deal */
    cdMinSpend: 'Not eligible for deal.  Minimum spend ',
    /* Disabled cart deal */
    cddMinSpend: 'Not eligible for deal.  Minimum spend ',
    /* Toppings popup */
    tpAdd: 'Add to order',
    tpOk: 'OK',
    tpRemove: 'Remove from order',
    tpCancel: 'Cancel',
    tpCancelDeal: 'Cancel',
    tpAddedCharges: 'Additional charges',
    tpItemPrice: 'Item price',
    tpQuantity: 'Quantity',
    tpItemType: 'Item type',
    tpCustomize: 'Customize your item',
    tpTickPrompt: 'Highlighted options are included free with this item.  Untick the options if you want to remove them.',
    tpFreeItems1: 'You have ',
    tpFreeItems2Singular: 'free option remaining',
    tpFreeItems2Multiple: 'free options remaining',
    tpRemainingItems1: 'You have ',
    tpRemainingItems2Singular: ' option remaining',
    tpRemainingItems2Multiple: ' options remaining',
    tpNoRemainingItems: 'Sorry, you can\'t add any more options',
    tpSingle: 'single',
    tpDouble: 'double',
    tpCommentsForChef: 'Comments for the Chef',
    tpExtraBits: 'Let us know if there are any special cooking requirements for this item:',
    tpForPeson: 'Who\'s this item for?',
    tpPerson: 'If you\'re ordering for multiple people let us know who this item is for:',
    tpmAddItem: 'Add an item to your order',
    tpmEditItem: 'Edit an item in your order',
    tpAcceptChanges: 'Update order',
    /* Deal popup */
    dpAddDeal: 'Add a deal to your order',
    dpPrompt: 'Please choose your deal items',
    dpMissing: 'Missing information!  Please select items highlighted in red.',
    /* Popup deal line */
    pdlItem: 'Item ',
    pdlCustomize: 'Customize',
    pdlCustomizeFree: 'Press customize to choose your free options',
    /* Popup deal line picker */
    pdlpCustomize: 'Customize',
    /* Deal popup (toppings) */
    dptOk: 'Ok',
    dptRemove: 'Remove from order',
    dptAdd: 'Add to order',
    dptCancel: 'Cancel',
    pdtItem: 'Item ',
    /* Login/register popup */
    lrpLogin: 'Sign in',
    lrCustomerDetails: 'Customer Details',
    lrpFacebookPrompt: 'If you\'re a facebook user you don\'t need to sign up for an account with our website',
    lrpSignInFacebookButton: 'Sign in with facebook',
    lrpDividerOr: 'OR',
    lrpAndroPrompt: 'Login using your email address and password',
    lrpAndroEmail: 'email address',
    lrpAndroPassword: 'password',
    lrpAndroLoginButton: 'Sign In',
    lrpSignUpText: 'Register & Order Now',
    lrpSignUpButton: 'new account',
    lrpCancelButton: 'Cancel',
    lrpRegister: 'Create new account?',
    /* Checkout */
    checkCheckout: 'Checkout',
    checkUpselling: '{index}) Anything else?',
    checkUpsellingTitle: 'Anything else?',
    checkUpsellButton: 'Add to basket',
    checkWhoAreYou: 'Who are you?',
    checkFirstName: 'First name: ',
    checkFirstNameEgP: 'e.g. Jack',
    checkSurname: 'Surname / family name: ',
    checkSurnameEgP: 'e.g. Smith',
    checkTel: 'Telephone number: ',
    checkTelEgP: '0123 456789 ',
    checkEmail: 'Email address: ',
    checkEmailEgP: 'e.g. jack.smith@example.com',
    checkMarketing: 'Let me know about new products and special offers',
    checkRememberContact: 'Remember my contact details for next time',
    checkMissing: 'Missing information!  Please enter details in the boxes highlighted in red.',
    checkCollectTime: 'Requested Collection Time',
    checkDeliverTime: 'Requested Delivery Time',
    checkSlotWarning: '',
    checkDeliveryAddress: 'Where do you want your order delivered to?',
    checkRememberAddress: 'Save this address to my profile',
    checkExtraInfo: 'Is there anything you need to tell us about this order?',
    checkDirections: 'Directions / notes',
    checkDirectionsEx: 'E.g. Turn left at the newsagents',
    checkDirectionsExP: 'E.g. Turn left at the newsagents',
    checkDelivNotes: 'Delivery notes:',
    checkDelivNotesEx: 'E.g. baby sleeping don\'t use doorbell',
    checkDelivNotesExP: 'E.g. baby sleeping don\'t use doorbell',
    checkChefNotes: 'Chef notes: ',
    checkChefNotesEx: 'E.g. make everything spicy please',
    checkChefNotesExP: 'E.g. make everything spicy please',
    checkRequired: '* Required',
    checkSTotal: 'TOTAL',
    checkSVoucherCode: 'Have a voucher code? Enter it here.',
    checkSAddVoucherCode: 'Apply Voucher',
    checkSAddVoucherTitle: 'Add voucher',
    checkSRedeemedLoyaltyPrompt1: 'Loyalty: ',
    checkSRedeemedLoyaltyPrompt2: ' points redeemed',
    checkSAddLoyaltyPrompt1: 'Loyalty points available ',
    checkSAddLoyaltyPrompt2: ' worth ',
    checkSAddLoyaltyPrompt3: ' loyalty points redeemed',
    checkSInvalidVoucher: 'Invalid voucher code',
    checkSIsBlankVoucher: 'Please enter voucher code',
    checkSVoucherNotForCollection: 'This voucher is not valid for collection orders',
    checkSVoucherNotForDelivery: 'This voucher is not valid for delivery orders',
    checkSVoucherMinOrderAmountNotMet: 'Minimum order value not met',
    checkSVoucherNotValidOnThisDate: 'Voucher is not valid today',
    checkSVoucherNotValidOnThisDayOfTheWeek: 'Voucher is not valid for this day of the week',
    checkSVoucherNotValidOnThisTimeOfTheDay: 'Voucher is not valid for this time of the day',
    checkSVoucherUsedTooManyTimesForCustomer: 'You have exceeded the number of times you can use this voucher',
    checkSAddLoyaltyTitle: "Loyalty",
    checkSAddLoyaltyAddButton: "Redeem Points",
    checkChangeAddress: 'Change Delivery Address',
    checkEnterAddress: 'Enter Delivery Address',
    checkSSubmitPayment: 'Take payment and complete order',
    checkSMinimumLoyaltyPoints: "You need at least {minPoints} points to redeem your loyalty points",
    whoAreYou: '{index}) Who are you?',
    collectionTime: '{index}) Collection time',
    deliveryTime: '{index}) Delivery time',
    deliveryAddress: '{index}) Delivery address',
    orderNotes: '{index}) Order notes',
    placeOrder: 'Place order',
    confirmOrder: 'Confirm order',
    next: 'Next',
    back: 'Back',
    pleaseSelectATime: '--- Please select a time ---',
    asSoonAsPossibleNoETD: 'As soon as possible (30-40 mins)',
    asSoonAsPossible: 'As soon as possible',
    preparingForPayment: 'Preparing for payment',
    sendingOrderToStore: 'Sending your order to the store',
    sendOrderToStore: 'Send order to store',
    checkoutPhone: 'Phone: ',
    /* Checkout order summary */
    checkSSummary: '{index}) Summary',
    checkSOrderSummary: 'Order summary',
    checkSOrderItemsTitle: 'Order items',
    checkSDeliveryTimeTitle: 'Delivery time',
    checkSCollectionTimeTitle: 'Collection time',
    checkSDeliveryAddressTitle: 'Delivery address',
    checkSCollectionAddressTitle: 'Collection address',
    checkSPaymentTitle: 'Order now using',
    checkSNoAddress: 'No address selected',
    checkSNoPayment: 'No payment selected',
    checkSPayNow: 'Credit Card',
    checkSPayLater: 'Cash',
    checkUseAddressAndSave: 'Use address and save it to my profile',
    checkUseAddressNoSave: 'Use address',
    checkCancelAddress: 'Cancel',
    /* Checkout payment */
    checkPayment: '{index}) Payment',
    checkPaymentTitle: 'Payment',
    /* Address */
    checkMissingInfoError: 'Missing information!  Please enter details in the boxes highlighted in red.',
    checkBadPostcode: 'Sorry, this store doesn\'t deliver to your postcode.',
    /* French address */
    org1_FR: 'Activité',
    org1_eg_FR: 'E.g. Service des ventes',
    org2_FR: 'Société',
    org2_eg_FR: 'E.g. Andromeda Trading Ltd.',
    prem1_FR: 'Appartement',
    prem1_eg_FR: 'E.g. 34',
    prem2_FR: 'Bâtiment',
    prem2_eg_FR: 'E.g. C',
    prem3_FR: 'Résidence',
    prem3_eg_FR: 'E.g. Le Grand Chêne',
    roadNumber_FR: 'Numéro de rue',
    roadNumber_eg_FR: 'E.g. 4',
    roadName_FR: 'Nom de rue',
    roadName_eg_FR: 'E.g. Rue Salvador Allende',
    userLocality1_FR: 'Etage',
    userLocality1_eg_FR: 'E.g. 1',
    userLocality2_FR: 'Digiphone',
    userLocality2_eg_FR: 'E.g. 555',
    userLocality3_FR: 'Interphone',
    userLocality3_eg_FR: 'E.g. 23',
    town_FR: 'Ville',
    town_eg_FR: 'E.g. Paris',
    postcode_FR: 'Code postal',
    postcode_eg_FR: 'E.g. 92100',
    /* UK address */
    org1_UK: 'Department:',
    org1_eg_UK: 'E.g. Sales Department',
    org1_egP_UK: 'E.g. Sales Department',
    org2_UK: 'Organisation name:',
    org2_eg_UK: 'E.g. Andromeda Trading Ltd.',
    org2_egP_UK: 'E.g. Andromeda Trading Ltd.',
    prem1_UK: 'House name: ',
    prem1_eg_UK: 'E.g. Flat 1 or \'Sandy Cottage\'',
    prem1_egP_UK: 'E.g. Flat 1 or \'Sandy Cottage\'',
    prem2_UK: 'Building name: ',
    prem2_eg_UK: 'E.g. Nelson Mandela House',
    prem2_egP_UK: 'E.g. Nelson Mandela House',
    //min line 1
    addressLine1: "Address line 1",
    roadNumber_UK: 'House number',
    roadNumber_eg_UK: 'E.g. 4',
    roadNumber_egP_UK: 'E.g. 4',
    //min line 2
    addressLine2: "Address line 2",
    roadName_UK: 'Road name',
    roadName_eg_UK: 'E.g. "Park Road"',
    roadName_egP_UK: 'E.g. "Park Road"',
    //min line 3
    town_UK: 'Town',
    town_eg_UK: 'The town name. E.g. "Ely"',
    town_egP_UK: 'The town name. E.g. "Ely"',
    userLocality1_UK: 'Locality: ',
    userLocality1_eg_UK: 'E.g. Town "London", Locality "Westminster"',
    userLocality1_egP_UK: 'E.g. Town "London", Locality "Westminster"',
    //min line 4
    postcode_UK: 'Postcode',
    postcode_eg_UK: 'E.g. "SM6 0DZ"',
    postcode_egP_UK: 'E.g. "SM6 0DZ"',
    postcodeHelp: 'don\'t forget the space!',
    /* Terms and conditions */
    tncTitle: 'Terms and conditions',
    tncNoTNC: 'There are currently no terms and conditions',
    /* Payment */
    payTitle: 'Payment',
    payPrompt: 'When would you like to pay for this order?',
    payAtDoor: 'Pay at door',
    payOnCollection: 'Pay on collection',
    payNow: 'Pay now',
    payTNC1: 'I have read and agree to the ',
    payTNC2: 'terms and conditions',
    payTNCWarn: 'You must agree to the terms and conditions before proceeding',
    payWarning: 'Once you have submitted your payment details please do not browse away from this page.  You may be charged multiple times for the order.',
    /* Datacash payment */
    /* Mercury payment */
    /* Mercanet payment */
    mercanetTitle: 'Payment',
    mercanetIntro: 'Please select a payment type and you will be re-directed to the payment providers\' web site.  Please note that you will no longer be able to modify your order after you have been re-directed.',
    mercanetiFrameWarn: 'Your browser does not support iFrames. To view this content, please download and use the latest version of one of the following browsers: Internet Explorer, Firefox, Google Chrome or Safari.',
    /* Popup mobile menu */
    pmmOptions: 'OPTIONS',
    pmmHome: 'STORE DETAILS',
    /* Mobile menu */
    mmOptions: 'OPTIONS',
    mmMenu: 'MENU',
    /* Mobile mode page headers */
    mmHome: 'HOME',
    mmOrderNow: 'MENU',
    mmMyOrder: 'MY ORDER',
    mmPostcodeCheck: 'POSTCODE CHECK',
    mmChangeStoreButton: 'SELECT STORE',
    mmReturnToParentWebsite: 'RETURN HOME',
    mmBack: "Back",
    /* Footer */
    termsOfUse: 'Terms of use',
    privacyPolicy: 'Privacy policy',
    cookiePolicy: 'Cookie policy',
    sitemap: 'Sitemap',
    footPoweredBy1: 'Powered by ',
    footPoweredBy2: 'Andromeda POS',
    copyright: '&copy; Andromeda Trading Ltd 2014.  All rights reserved.',
    newsletter: 'Signup for news',
    /* Submit order view */
    sovOneMoment: 'One moment please',
    sovCheckingStoreStatus: 'Checking store status',
    sovCheckingVoucherCode: 'Checking voucher code',
    sovPreparingPayment: 'Preparing for payment',
    /* Order accepted view */
    oavOrderAcepted: 'Your order has been accepted by the store',
    oavOrderPending: 'Your order has been sent to the store.  We\'ll send you an email when the store confirms the order.  Your order number is {orderNumber}',
    oavThanks: 'Thanks for your order!',
    oavReturnToMenu: 'Return to the menu',
    oavLoyaltyPointsWarning: 'Please note that it may take up to 48 hours for any gained loyalty points to be applied to your account',
    /* Wait for order page */
    wfopConnecting: 'Please wait.  Connecting to server...',
    wfopPleaseWait: 'Please wait.  Sending you order to the store...',
    wfopOrderAccepted: 'Your order has been accepted by the store',
    wfopOrderPending: 'Your order has been sent to the store.  We\'ll send you an email when the store confirms the order.  Your order number is {orderNumber}',
    wfopACSFailed: 'Sorry, there was a problem sending your order to the store.  Please contact the store to check that they have received it.  Error code ',
    wfopServerFailed: 'Sorry, there was a problem sending your order to the store.  Please contact the store to check that they have received it.',
    wfopConnectionLost: 'Connection to server lost.  Trying to reconnect...',
    wfopConnectionLostWaiting: 'Connection to server lost.  Waiting to reconnect...',
    /* Error messages */
    errInternalApplicationError: 'There was an error in the application',
    errProblemGettingSites: 'Sorry, this store is not currently available',
    errProblemGettingSiteDetails: 'There was a problem getting the site details',
    errProblemGettingVoucherDetails: 'There was a problem getting the voucher details',
    errProblemGettingSiteMenu: 'There was a problem getting the site menu',
    errProblemGettingAccountDetails: 'There was a problem getting the account details',
    errProblemUpdatingAccountDetails: 'There was a problem updating the account details',
    errProblemCreatingAccountDetails: 'There was a problem creating the account details',
    errProblemResettingPassword: 'There was a problem resetting the account password',
    errProblemRequestingAPasswordReset: 'There was a problem requesting a password reset',
    errProblemGettingOrders: 'There was a problem getting the account orders',
    errProblemGettingOrder: 'There was a problem getting the order',
    errDefaultWebErrorMessage: 'Sorry, there was a technical glitch!  If the problem persists please contact the store directly to place your order and let them know there is a problem with the website',
    errDefaultInternalErrorMessage: 'Sorry, there was a technical glitch!  If the problem persists please contact the store directly to place your order and let them know there is a problem with the website. (internal)',
    errDefaultPaymentErrorMessage: 'Sorry, there was a payment problem!  If the problem persists please contact the store directly to place your order and let them know there is a problem with the website',
    errCommsProblem: 'Sorry, there was a communications problem!  If the problem persists please contact the store directly to place your order and let them know there is a problem with the website. (comms error)',
    errProblemInitialisingPayment: 'There was a problem initialising the payment',
    errSendToStoreFailedPaymentCancelled: 'Sorry, there was a problem sending your order to the store.  Payment has been cancelled.  You can try again or contact the store directly to place your order.',
    errSendToStoreFailedPaymentCancelFailed: 'Sorry, there was a problem sending your order to the store.  There was a problem cancelling the payment.  Please contact the store directly to place your order and arrange for a refund.',
    errAppendErrorCode: '. Error code ',
    errProblemVoucherErrorGeneral: 'There was a problem validating the voucher',
    errProblemSubmittingFeedback: 'There was a problem submitting your feedback',
    pleaseSelectAnItem: '-- Please select an item --',
    gettingStoreDetails: 'Getting store details',
    loadingMenu: 'Loading menu',
    downloadingStoreMenu: 'Downloading store menu',
    savingMenuToDevice: 'Saving menu to your device',
    renderingMenu: 'Rendering menu',
    // Prefixed to additional topping names in "Your Order" sidebar (cart/basket)
    prefixAddTopping: 'Add ',
    // Prefixed to additional topping names in "Your Order" sidebar (cart/basket)
    prefixAddDoubleTopping: 'Add double ',
    // Prefixed to remove topping names in "Your Order" sidebar (cart/basket)
    prefixRemove: 'Remove ',
    // Appended to some error messages
    appendErrorCode: '. Error code ',
    // Appended to some error messages
    appendUnknownErrorCode: '. Error code unknown',
    orderRejected: 'Sorry, the store automatically rejected your order due to a technical problem.  If the problem persists please contact the store directly to place your order and let them know there is a problem with the website.  Error code ',
    cantDeliverOrder: 'Sorry, there may have been a problem sending your order to the store.  Please contact the store to check that they have received it.  Error code ',
    apiProblem: 'Sorry, there was a problem sending your order to the store.  Please try again.  If the problem persists please contact the store directly to place your order and let them know there is a problem with the website.  Error code ',
    // Do NOT translate or remove the text "{ErrorMessage}"
    cardProcessingError: 'Sorry, there was a payment problem!  The card payment provider returned the following message {ErrorMessage}.  If the problem persists please contact the store directly to place your order.',
    // Appended after the store name if it's not taking orders
    appendOffline: ' - Sorry, not taking online orders right now',
    openAllDay: 'Open all day',
    closed: 'Closed',
    // Do NOT translate, modify or remove the text "{from}" and "{to}".  It will be automatically replaced with times e.g. '11:00am to 2:30pm'
    fromTo: '{from} to {to}',
    // Only displayed when a deals minimum order value is not met.  Do NOT translate, modify or remove the text "{price}".
    minimumOrderValue: 'Deal not allowed - order price must be at least {price}',
    // Do NOT translate, modify or remove the text "{item}".  It will be automatically replaced with a category name or item name e.g. 'stuffed crust'
    premiumChargeFor: 'Premium charge for {item}',
    /* Address prefixes */
    prem1Prefix: '',
    prem2Prefix: '',
    prem3Prefix: '',
    userLocality1Prefix: '',
    userLocality2Prefix: '',
    userLocality3Prefix: '',
    /* Information */
    infBack: 'Back',
    infPrivacyPolicy: '',
    infTermsOfUse: '',
    infCookiePolicy: '',
    /* Feedback */
    feedbackPrompt: 'You can use this form to provide feedback to us about this website or your order',
    feedbackName: 'Your name:',
    feedbackEmail: 'Your email address:',
    feedbackCategory: 'Nature of the feedback:',
    feedbackFeedback: 'Feedback:',
    feedbackOptional: '(optional)',
    selectAFeedbackCategory: 'Please choose a category...',
    feedbackCatWebsiteProblem: 'Problem with the website',
    feedbackCatGeneralWebsite: 'General feedback about the website',
    feedbackCatStore: 'Feedback about the store',
    feedbackSubmitButton: 'Submit',
    feedbackMissingError: 'Please enter some feedback',
    feedbackCategoryMissingError: 'Please select the nature of the feedback',
    feedbackSuccess: 'Your feedback has been successfully submitted.  Thanks for taking the time to give us your feedback!',
    feedbackServerError: 'There was a technical problem submitting your feedback.  Please try again later.',
    feedbackSubmitting: 'Submitting feedback'
};
//# sourceMappingURL=en-Gb.js.map