/*
    Copyright © 2014 Andromeda Trading Limited.  All rights reserved.
    THIS FILE AND ITS CONTENTS ARE PROTECTED BY COPYRIGHT AND/OR OTHER APPLICABLE LAW.
    ANY USE OF THE CONTENTS OF THIS FILE OR ANY PART OF THIS FILE WITHOUT EXPLICIT PERMISSION FROM ANDROMEDA TRADING LIMITED IS PROHIBITED.
*/
/* Text displayed on the web site */
var frenchTextStrings = {
    dealsSection: 'Promos',
    noRestaurants: 'Il n\'y a pas de restaurants',
    /* General */
    gExitWarning: 'AVERTISSEMENT: Vous avez actuellement obtenu des articles dans votre panier. Si vous continuez votre panier sera effacé.',
    /* Header */
    hPhone: 'Tel. ',
    hDeliveryAreaButton: 'Vérifiez si vous êtes dans notre zone de livraison',
    hChangeStoreButton: 'Sélectionnez un autre restaurant',
    hOrderNowButton: 'Commandez',
    hHomeButon: 'Acceuil',
    hReturnToParentWebsiteButton: 'Retourner à l\'accueil',
    hSupportEmailPrompt: 'Email: ',
    hTwitter: '',
    hInstagram: '',
    hFacebook: '',
    hPinterest: '',
    /* Header: Site selector */
    hSiteSelectorPostcodePrompt: 'Permet de vérifier votre code postal et de voir si nous pouvons vous livrer',
    hSiteSelectorPostcodeExample: 'ex. 75016',
    hSiteSelectorPostcodeButton: 'GO',
    hSiteSelectorNoPostcode: 'Please enter a postcode',
    hBadDeliveryZone: 'Désolé, nous ne livrons pas à votre code postal',
    hShowAllRestaurants: 'Montrer tous les restaurants',
    hLoginPrompt: 'login',
    hLoginButton: 'ok',
    hForgetPasswordButton: 'forgot password',
    hRegisterButton: 'register',
    hMyProfileButton: 'My profile',
    hMyOrdersButton: 'My orders',
    hLogoutButton: 'Logout',
    hUsernamePlaceholder: 'username',
    hPasswordPlaceholder: 'password',
    hLoggingIn: 'Logging in',
    hMissingEmail: 'Please enter an email address',
    hMissingPassword: 'Please enter a password',
    hUnableToLogin: 'Unable to login',
    hInvalidUserPass: 'Invalid username or password',
    hHelloLoggedIn: 'Hello {firstName}, you\'re ordering from {storeName}',
    hHelloNotLoggedIn: 'You\'re ordering from {storeName}',
    hHelloLoggedInNoStore: 'Hello {firstName}',
    /* Mobile header */
    hmLoginButton: 'Login',
    hmMyBasketButton: 'My basket',
    hmLoginRegisterButton: 'Login/Register',
    /* HOME */
    homeStoreDetailsTitle: 'Welcome to our Pizza Shop',
    homeStoreDetails: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    homeMenuTitle: 'Menu and Ordering',
    homeMenu: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    homeStoreDetailsButton: 'Learn More &gt;',
    homeMenuButton: 'Order online',
    /* SITE LIST */
    slChooseRestaurant: 'Veuillez choisir votre restaurant',
    slSorry: 'Sorry we do not deliver to your postcode!',
    slChangePostcodePrompt: 'For postcode ',
    slChangePostcodeButton: 'Change postcode',
    slSelectPostcodeButton: 'Or select a postcode for delivery',
    /* Menu */
    mMenuSections: 'Sections du menu',
    /* My Order sidebar */
    sMyOrder: 'Mon Panier',
    sDeliverToDoor: 'Me faire livrer',
    sCollectFromStore: 'Aller chercher en boutique',
    sModifyOrder: 'Modifier commande',
    sReturnToCheckout: 'Retour au paiement',
    sOffline: 'Ce restaurant n\'accepte pas les commandes en lignes actuellement. Veuillez verifier ulterieurement ou commander directement en boutique.',
    sEmpty1: 'Pas de produits dans votre commande',
    sEmpty2: '',
    sItemCount1: 'Il y a ',
    sItemCount2: ' article/s dans votre commande',
    sSubTotal: 'Subtotal',
    sOrderTotal: 'Total commande',
    sInvalid: 'Un ou plusieurs articles dans votre commande n\'est pas valuable et sera automatiquement enlevé de la commande lors de la validation',
    sClear: 'Effacer',
    sCheckout: 'Validation',
    sBackToMenu: 'Retour au menu',
    sRemove: 'Cliquez sur un produit pour le modifier ou enlever',
    sMinimumDelivOrder: 'Minimum de commande ',
    sStoreClosed: 'Sorry, the store is closed',
    /* Image view */
    ivClose: 'Cliquez sur l\'image pour la cacher',
    /* Menu item (Menu) */
    miQuantity: 'Quantité',
    miAdd: 'Ajouter à la commande',
    /* Deals (Menu) */
    dAdd: 'Ajouter à la commande',
    dCollectOnly: 'à emporter seulement',
    dDeliverOnly: 'Seulement me faire livrer',
    dNotToday: 'Cette promo n\'est pas disponible aujourd\'hui',
    dMinSpend: 'Minimum commande ',
    /* Please wait */
    pwOneMomentPlease: 'Un instant svp',
    /* Store selector */
    ssStoreSelector: 'Les restaurants suivants livrent dans votre code postal',
    //ssOrderFoodNow: 'Order food now', ?? not needed?
    ssShowMeAllTheRestaurants: 'Montrer tous les restaurants',
    ssCollect: 'Vous pouvez aussi chercher votre commande dans les boutiques suivantes',
    /* Store selector */
    sselStoreSelector: 'Choisir restaurant',
    /* Reset password */
    prPasswordRetrieval: 'Password reset',
    prPasswordRetrievalInstructions: 'Please enter the email address you used when you registered.  We will send you an email containing instructions for how to reset your password.',
    prEmail: 'Email',
    prRetrievalPassword: 'Reset password',
    prCancel: 'Cancel',
    prEmailSent: 'We have sent you an email containing instructions for resetting your password',
    prGenericError: 'Sorry, there was a technical problem resetting your password',
    prNoEmail: 'Please enter your email address',
    prInvalidEmail: 'Please enter a valid email address',
    prNoPassword: 'Please enter your new password',
    prNoRepeatPassword: 'Please repeat your new password',
    prPasswordsDoNotMatch: 'Password and repated password do not match',
    prPassword: 'New password',
    prRepeatPassword: 'Re-enter new password',
    prPasswordToShort: 'Password must be at least 4 characters',
    prPasswordReset: 'Password reset',
    /* Register */
    lrLoginRegister: 'Login / register',
    lrLoginEmail: 'Email address',
    lrLoginPassword: 'Password',
    lrLoginButton: 'Login',
    lrWhoAreYou: 'Who are you?',
    lrFirstName: 'First name',
    lrFirstNameEgP: 'e.g. Jack',
    lrSurname: 'Surname',
    lrSurnameEgP: 'e.g. Smith',
    lrEmail: 'Email address',
    lrEmailEgP: 'e.g. jack.smith@example.com',
    lrPassword: 'Password',
    lrReenterPassword: 'Re-enter password',
    lrPhoneNumber: 'Phone number',
    lrPhoneNumberEgP: 'e.g. 0123 456789',
    lrEmailMarketting: 'Let me know about new products and special offers',
    lrSMSMarketting: 'Let me know about new products and special offers',
    lrCreateAccountAddress: 'Where do you want your orders delivered to',
    lrRegisterButton: 'Register',
    lrCancelButton: 'Cancel',
    lrMissingPassword: 'Please enter a password',
    lrMissingReneterPassword: 'Please re-enter the password',
    lrPasswordsDontMatch: 'The two passwords do not match',
    lrPasswordTooShort: 'Password must be at least 4 characters',
    lrMissingFirstName: "Please enter your first name",
    lrMissingSurname: "Please enter your surname",
    lrMissingEmail: "Please enter your email address",
    lrEmailNotValid: "Please enter a valid email address",
    lrPhoneMissing: "Please enter your phone number",
    lrMissingRoadName: "Please enter your road name",
    lrMissingTown: 'Please enter your town',
    lrPasswordMismatch: 'Passwords do not match',
    lrPassToShort: 'Password must be at least 4 characters',
    lrRegistering: 'Creating your account',
    lrEmailAlreadyUsed: 'This email address has already been used',
    lrUnableToCreateAccount: 'Unable to create account',
    lrMissingPostcode: 'S\'il vous plaît, entrez votre code postal',
    lrInvalidPostcode: 'Please enter a valid postcode',
    lrInvalidPhoneNumber: 'Please enter valid phone number',
    lrInvalidPhoneNumberMaxLength: 'Please enter valid phone number (Maximum Allowed: upto 15 digits)',
    /* My Profile */
    mpMyProfile: 'My profile',
    mpWhoAreYou: 'Who are you',
    mpChangePassword: 'Change password',
    mpCurrentPassword: 'Current password',
    mpNewPassword: 'New password',
    mpConfirmNewPassword: 'Confirm new password',
    mpMyOrders: 'My orders',
    mpBackToMenu: 'Back to menu',
    mpSaveChangesButton: 'Save changes',
    mpMissingPasswords: 'If you want to change your password please enter you current password and the new passsword twice',
    mpWrongCurrentPassword: 'Wrong password',
    mpUnableToCreateAccount: 'Unable to save account changes',
    /* My orders */
    moQuantity: 'Quantity',
    moPrice: 'Price',
    moOrderTotal: 'Order total',
    moRepeatOrder: 'Repeat order',
    moError: 'Sorry, unable to retrieve your orders',
    moNoOrders: 'You have not placed any orders',
    moPleaseWaitOrders: 'Please wait ... getting orders',
    moPleaseWaitOrder: 'Please wait ... getting order',
    /* Repeat order */
    roRepeatOrder: 'Repeat order',
    roDiscontinued: 'Sorry, this product has been discontinued',
    roOrderTotal: 'Order total',
    roAddToCart: 'Add items to my basket',
    roBack: 'Back to my profile',
    roOrderTotalPrompt: 'Order total',
    /* Store details */
    storeDetailsDeliveryTimes: 'Nous livrons entre les horaires suivants',
    storeDetailsMonday: 'Lundi',
    storeDetailsTuesday: 'Mardi',
    storeDetailsWednesday: 'Mercredi',
    storeDetailsThursday: 'Jeudi',
    storeDetailsFriday: 'Vendredi',
    storeDetailsSaturday: 'Samedi',
    storeDetailsSunday: 'Dimanche',
    /* Cart item */
    ciCollectOnly: 'Seulement venir chercher en boutique',
    ciDeliverOnly: 'Seulement me faire livrer',
    /* Disabled cart item */
    dciCollectOnly: 'Seulement venir chercher en boutique',
    dciDeliverOnly: 'Deliver to door only',
    /* Cart deal */
    cdMinSpend: 'Pas éligible pour la promo. Minimum commande ',
    /* Disabled cart deal */
    cddMinSpend: 'Pas éligible pour la promo. Minimum commande ',
    /* Toppings popup */
    tpAdd: 'Ajouter à la commande',
    tpOk: 'OK',
    tpRemove: 'Enlever de la commande',
    tpCancel: 'Annuler',
    tpCancelDeal: 'Annuler',
    tpAddedCharges: 'Suppléments',
    tpItemPrice: 'Prix produit',
    tpQuantity: 'Quantité',
    tpItemType: 'Type de produit',
    tpCustomize: 'Personnalisez votre produit',
    tpTickPrompt: 'Les options soulignées sont incluses avec ce produit. Décochez les options si vous voulez les enlever',
    tpFreeItems1: 'Vous avez ',
    tpFreeItems2: 'option/s gratuites restantes',
    tpFreeItems2Singular: 'option/s gratuites restantes',
    tpFreeItems2Multiple: 'option/s gratuites restantes',
    tpSingle: 'simple',
    tpDouble: 'double',
    tpCommentsForChef: 'Commentaires pour le chef',
    tpExtraBits: 'Veuillez nous informer si vous auriez des remarques pour cuisson de ce produit:',
    tpForPeson: 'Pour qui est ce produit?',
    tpPerson: 'Si vous commandez pour plusieurs personnes, veuillez nous indiquer pour qui est ce produit:',
    tpmAddItem: 'Add an item to my order',
    tpmEditItem: 'Edit an item in my order',
    tpAcceptChanges: 'Update order',
    /* Deal popup */
    dpAddDeal: 'Add a deal to your order',
    dpPrompt: 'Sélectionnez les produits de votre promo',
    dpMissing: 'Informations manquantes! Veuillez sélectionner les produits soulignés en rouge.',
    /* Popup deal line */
    pdlItem: 'Produit ',
    pdlCustomize: 'Personnaliser',
    pdlCustomizeFree: 'Appuyez personnaliser pour sélectionner vos options gratuites',
    /* Popup deal line picker */
    pdlpCustomize: 'Personnaliser',
    /* Deal popup (toppings) */
    dptOk: 'Ok',
    dptRemove: 'Enlever de la commande',
    dptAdd: 'Ajouter à la commande',
    dptCancel: 'Annuler',
    pdtItem: 'Produit',
    /* Login/register popup */
    lrpLogin: 'Sign in',
    lrpFacebookPrompt: 'If you\'re a facebook user you don\'t need to sign up for an account with our website',
    lrpSignInFacebookButton: 'Sign in using facebook',
    lrpDividerOr: 'OR',
    lrpAndroPrompt: 'Sign in using the email address and password you used when you created your account',
    lrpAndroEmail: 'Email address',
    lrpAndroPassword: 'Password',
    lrpAndroLoginButton: 'Login',
    lrpSignUpButton: 'Sign up',
    lrpCancelButton: 'Cancel',
    /* Checkout */
    checkCheckout: 'Validation',
    checkAnythingElse: 'Anything else?',
    checkWhoAreYou: 'Qui êtes-vous?',
    checkFirstName: 'Prénom: ',
    checkSurname: 'Nom de famille: ',
    checkTel: 'Numéro téléphone: ',
    checkEmail: 'Adresse email: ',
    checkMarketing: 'M\'informer au sujet de nouveaux produits et offres spéciales',
    checkRememberContact: 'Sauvegarder mes coordonnées pour la prochaine fois',
    checkCollectTime: 'Quand voulez-vous venir chercher votre commande?',
    checkDeliverTime: 'Quand voulez-vous vous faire livrer votre commande?',
    checkSlotWarning: '',
    checkMissing: 'Informations manquantes! Veuillez remplir les champs soulignés en rouge.',
    /* Address */
    checkMissingInfoError: 'Informations manquantes! Veuillez remplir les cases soulignées en rouge.',
    checkRequired: '* Requis',
    checkBadPostcode: 'solé, cette boutique ne livre pas à votre adresse.',
    /* French address */
    org1_FR: 'Activité',
    org1_eg_FR: 'Ex Service des ventes',
    org2_FR: 'Société',
    org2_eg_FR: 'Ex Andromeda Trading Ltd.',
    prem1_FR: 'Appartement',
    prem1_eg_FR: 'Ex 34',
    prem2_FR: 'Bâtiment',
    prem2_eg_FR: 'Ex C',
    prem3_FR: 'Résidence',
    prem3_eg_FR: 'Ex Le Grand Chêne',
    roadNumber_FR: 'Numéro de rue',
    roadNumber_eg_FR: 'Ex 4',
    roadName_FR: 'Nom de rue',
    roadName_eg_FR: 'Ex Rue Salvador Allende',
    userLocality1_FR: 'Etage',
    userLocality1_eg_FR: 'Ex 1',
    userLocality2_FR: 'Digiphone',
    userLocality2_eg_FR: 'Ex 555',
    userLocality3_FR: 'Interphone',
    userLocality3_eg_FR: 'Ex 23',
    town_FR: 'Ville',
    town_eg_FR: 'Ex Paris',
    postcode_FR: 'Code postal',
    postcode_eg_FR: 'Ex 92100',
    checkDeliveryAddress: 'Où voulez-vous que votre commande soit livrée?',
    checkRememberAddress: 'Sauvegarder cette adresse pour la prochaine fois',
    checkExtraInfo: 'Avez vous des remarques additionnelles pour cette commande?',
    checkDirections: 'Indications pour livreur: ',
    checkDirectionsEx: 'Ex. tourner à gauche près du kiosque à journaux',
    checkDelivNotes: 'Notes pour livraison: ',
    checkDelivNotesEx: 'Ex. bébé dort, ne pas sonner',
    checkChefNotes: 'Notes pour chef: ',
    checkChefNotesEx: 'Ex. bien pimenter svp',
    /* Checkout order summary */
    checkSSummary: '{index} Sumamry',
    checkSOrderSummary: 'Order sumamry',
    checkSOrderItemsTitle: 'Order items',
    checkSDeliveryTimeTitle: 'Delivery time',
    checkSCollectionTimeTitle: 'Collection time',
    checkSDeliveryAddressTitle: 'Delivery address',
    checkSCollectionAddressTitle: 'Collection address',
    checkSPaymentTitle: 'Payment',
    checkSNoAddress: 'No address selected',
    checkSNoPayment: 'No payment selected',
    checkSPayNow: 'Card',
    checkSPayLater: 'Cash',
    checkSTotal: 'TOTAL',
    checkSAddVoucherTitle: 'Discount vouchers',
    checkSInvalidVoucher: 'Invalid voucher code',
    checkSIsBlankVoucher: 'Please enter voucher code',
    checkSVoucherNotForCollection: 'This voucher is not valid for collection orders',
    checkSVoucherNotForDelivery: 'This voucher is not valid for delivery orders',
    checkSVoucherMinOrderAmountNotMet: 'Minimum order value not met',
    checkSVoucherNotValidOnThisDate: 'Voucher is not valid today',
    checkSVoucherNotValidOnThisDayOfTheWeek: 'Voucher is not valid for this day of the week',
    checkSVoucherNotValidOnThisTimeOfTheDay: 'Voucher is not valid for this time of the day',
    checkSVoucherUsedTooManyTimesForCustomer: 'You have exceeded the number of times you can use this voucher',
    checkChangeAddress: 'Change Delivery Address',
    checkUseAddressAndSave: 'Use address and save it to my profile',
    checkUseAddressNoSave: 'Use address',
    checkCancelAddress: 'Cancel',
    /* Checkout payment */
    checkPayment: '{index} Payment',
    checkPaymentTitle: 'Payment',
    checkSVoucherCode: 'Voucher code:',
    checkSAddVoucherCode: 'Add',
    /* Terms and conditions */
    tncTitle: 'Termes et conditions',
    tncNoTNC: 'Pas de termes et conditions actuellement',
    /* Payment */
    payTitle: 'Paiement',
    payPrompt: 'Quand voudriez-vous payer pour cette commande?',
    payAtDoor: 'Payer au livreur',
    payOnCollection: 'Payer en boutique',
    payNow: 'Payer maintenant',
    payTNC1: 'Lu et approuvé ',
    payTNC2: 'Termes et conditions',
    payTNCWarn: 'Vous devez approuver les termes et conditions avant de procéder',
    /* Datacash payment */
    /* Mercury payment */
    /* Mercanet payment */
    mercanetTitle: 'Paiement',
    mercanetIntro: 'Veuillez sélectionner un type de paiement et vous serez redirigés au site\s marchand\s. Veuillez noter qu’il ne vous sera plus possible de modifier votre commande après être redirigés.',
    mercanetiFrameWarn: 'Votre browser ne supporte pas iFrames. Pour voir ce contenu veuillez svp télécharger et utiliser la dernière version d’un des browsers suivants : Explorer, Firefox, Google Chrome ou Safari.',
    /* Popup mobile menu */
    pmmOptions: 'OPTIONS',
    pmmHome: 'ACCEUIL',
    pmmOrderNow: 'COMMANDER MAINTENANT',
    pmmMyOrder: 'MA COMMANDE',
    pmmChangeStoreButton: 'MAGASIN SELECT',
    pmmPostcode: 'VERIFICATION CODE POSTAL',
    pmmReturnToParentWebsite: 'RETOURNET à L\'ACCUEIL',
    /* Mobile menu */
    mmOptions: 'OPTIONS',
    mmMenu: 'MENU',
    /* Mobile mode page headers */
    mmHome: 'ACCEUIL',
    mmOrderNow: 'COMMANDER MAINTENANT',
    mmMyOrder: 'MA COMMANDE',
    mmPostcodeCheck: 'VERIFICATION CODE POSTAL',
    mmChangeStoreButton: 'MAGASIN SELECT',
    mmReturnToParentWebsite: 'RETOURNET à L\'ACCUEIL',
    /* Footer */
    termsOfUse: 'Terms of use',
    privacyPolicy: 'Privacy policy',
    cookiePolicy: 'Cookie policy',
    sitemap: 'Sitemap',
    footPoweredBy1: 'Propulsé par ',
    footPoweredBy2: 'Andromeda POS',
    /* Submit order view */
    sovOneMoment: 'Un moment svp',
    sovCheckingStoreStatus: 'Vérification de l\'état du magasin',
    sovCheckingVoucherCode: 'Vérification de code de réduction',
    sovPreparingPayment: 'Preparing for payment',
    /* Order accepted view */
    oavOrderAcepted: 'Votre commande a été acceptée au restaurant',
    oavOrderPending: 'Votre commande a été envoyée à la boutique. Nous \'vous enverrons un e-mail lorsque le magasin confirme la commande..  Votre numéro de commande est {orderNumber}',
    oavThanks: 'Nous vous remercions pour votre commande!',
    oavReturnToMenu: 'Retour au menu',
    /* Wait for order page */
    wfopConnecting: 'Veuillez patienter.  Connexion au serveur...',
    wfopPleaseWait: 'Veuillez patienter.  Commande envoyée au restaurant...',
    wfopOrderAccepted: 'Votre commande a été acceptée au restaurant',
    wfopOrderPending: 'Votre commande a été envoyée à la boutique. Nous \'vous enverrons un e-mail lorsque le magasin confirme la commande.  Votre numéro de commande est {orderNumber}',
    wfopACSFailed: 'Désolé, il y a eu un problème avec votre commande.  Veuillez svp appeler le restaurant et vérifier si elle a été reçue.  Code Erreur ',
    wfopServerFailed: 'Désolé, il y a eu un problème avec votre commande.  Veuillez svp appeler le restaurant et vérifier si elle a été reçue.',
    wfopConnectionLost: 'Connexion au serveur perdue.  Essai de réconnexion...',
    wfopConnectionLostWaiting: 'Connexion au serveur perdue.  En attentei de réconnexion...',
    /* Error messages */
    errInternalApplicationError: 'Il y avait une erreur dans l\'application',
    errProblemGettingSites: 'There was a problem getting the sites',
    errProblemGettingSiteDetails: 'Il y a eu un problème pour obtenir les coordonnées boutique',
    errProblemGettingSiteMenu: 'There was a problem getting the site menu',
    errProblemGettingAccountDetails: 'There was a problem getting the account details',
    errProblemUpdatingAccountDetails: 'There was a problem updating the account details',
    errProblemCreatingAccountDetails: 'There was a problem creating the account details',
    errProblemResettingPassword: 'There was a problem resetting the account password',
    errProblemRequestingAPasswordReset: 'There was a problem requesting a password reset',
    errProblemGettingOrders: 'There was a problem getting the account orders',
    errProblemGettingOrder: 'There was a problem getting the order',
    errDefaultWebErrorMessage: 'Désolé, il y a un problème technique. S\'il persiste veuillez svp contacter directement le restaurant pour commander et prévenir au sujet du problème en ligne',
    errDefaultInternalErrorMessage: 'Désolé, il y a un problème technique. S\'il persiste veuillez svp contacter directement le restaurant pour commander et prévenir au sujet du problème en ligne. (interne)',
    errDefaultPaymentErrorMessage: 'Désolé, il y a un problème avec le paiement. S\'il persiste veuillez svp contacter directement le restaurant pour commander et prévenir au sujet du problème en ligne',
    errCommsProblem: 'Désolé, il y a un problème de communication. S\'il persiste veuillez svp contacter directement le restaurant pour commander et prévenir au sujet du problème en ligne (erreur comm.)',
    errProblemInitialisingPayment: 'Il y a eu un problème avec l\'initialisation du paiement',
    errSendToStoreFailedPaymentCancelled: 'Désolé, un problème d\'envoi de votre commande au magasin. Le paiement a été annulé. Vous pouvez essayer de nouveau ou communiquez directement avec le magasin pour passer votre commande.',
    errSendToStoreFailedPaymentCancelFailed: 'Désolé, un problème d\'envoi de votre commande au magasin. Il y avait un problème d\'annuler le paiement. S\'il vous plaît contacter directement le magasin pour passer votre commande et obtenir un remboursement',
    errAppendErrorCode: '. Error code ',
    errProblemVoucherErrorGeneral: 'There was a problem validating the voucher',
    errProblemSubmittingFeedback: 'There was a problem submitting your feedback',
    pleaseSelectAnItem: '--Veuillez sélectionner un produit –-',
    gettingStoreDetails: 'Obtenir coordonnées boutique',
    loadingMenu: 'Téléchargement du menu',
    downloadingStoreMenu: 'Téléchargement du menu du restaurant',
    savingMenuToDevice: 'Sauvegarde du menu sur votre terminal',
    renderingMenu: 'Traduction menu',
    // Prefixed to additional topping names in "Your Order" sidebar (cart/basket)
    prefixAddTopping: 'Ajouter ',
    // Prefixed to additional topping names in "Your Order" sidebar (cart/basket)
    prefixAddDoubleTopping: 'Ajouter double ',
    // Prefixed to remove topping names in "Your Order" sidebar (cart/basket)
    prefixRemove: 'Enlever ',
    whoAreYou: 'Qui êtes-vous?',
    collectionTime: 'Heure de récupération',
    deliveryTime: 'Heure de livraison',
    deliveryAddress: 'Adresse de livraison',
    orderNotes: 'Notes commandes',
    placeOrder: 'Commander',
    confirmOrder: 'Confirm order',
    next: 'Suivant',
    back: 'Retour',
    pleaseSelectATime: '--- Veuillez sélectionner une heure ---',
    asSoonAsPossibleNoETD: 'Au plus vite (30-40 min)',
    asSoonAsPossible: 'Au plus vite',
    preparingForPayment: 'Préparation paiement',
    sendingOrderToStore: 'Envoi de commande au restaurant',
    // Appended to some error messages
    appendErrorCode: '. Code erreur ',
    // Appended to some error messages
    appendUnknownErrorCode: '. Code erreur inconnu',
    orderRejected: 'Désolé, il y a un problème – votre commande a été automatiquement rejetée. Si le problème persiste veuillez svp contacter directement le restaurant pour commander et prévenir au sujet du problème en ligne. Code erreur ',
    cantDeliverOrder: 'Désolé, il y a un problème avec envoi de votre commande. Si le problème persiste veuillez svp contacter directement le restaurant pour commander et prévenir au sujet du problème en ligne. Code erreur ',
    apiProblem: 'Désolé, il y a un problème avec envoi de votre commande. Réessayez svp et si le problème persiste veuillez svp contacter directement le restaurant pour commander et prévenir au sujet du problème en ligne. Code erreur ',
    // Do NOT translate or remove the text "{ErrorMessage}"
    cardProcessingError: 'Désolé, il y a un problème avec le paiement. Le site marchand a envoyé le message suivant {ErrorMessage}. Si le problème persiste veuillez svp contacter directement le restaurant pour commander et prévenir au sujet du problème en ligne. Code erreur ',
    // Appended after the store name if it's not taking orders
    appendOffline: ' – Desolé, pas de commandes en ligne en ce moment',
    openAllDay: 'Ouvert toute lq journée',
    closed: 'Fermé',
    // Do NOT translate, modify or remove the text "{from}" and "{to}".  It will be automatically replaced with times e.g. '11:00am to 2:30pm'
    fromTo: '{from} à {to}',
    // Only displayed when a deals minimum order value is not met.  Do NOT translate, modify or remove the text "{price}".
    minimumOrderValue: 'Promo  non permise – la valeur de la commande doit être au moins {price}',
    // Do NOT translate, modify or remove the text "{item}".  It will be automatically replaced with a category name or item name e.g. 'stuffed crust'
    premiumChargeFor: 'Supplement',
    /* Address prefixes */
    prem1Prefix: 'Appt. ',
    prem2Prefix: 'Bat. ',
    prem3Prefix: 'Rés. ',
    userLocality1Prefix: 'Etg. ',
    userLocality2Prefix: 'Digi. ',
    userLocality3Prefix: 'Iphone. ',
    /* Information */
    infBack: 'Back',
    infPrivacyPolicy: '',
    infTermsOfUse: '',
    infCookiePolicy: '',
    /* Feedback */
    feedbackPrompt: 'You can use this form to provide feedback to us about this website or your order',
    feedbackName: 'Your name:',
    feedbackEmail: 'Your email address:',
    feedbackCategory: 'Nature of the feedback:',
    feedbackFeedback: 'Feedback:',
    feedbackOptional: '(optional)',
    feedbackCatWebsiteProblem: 'Problem with the website',
    feedbackCatGeneralWebsite: 'General feedback about the website',
    feedbackCatStore: 'Feedback about the store',
    feedbackSubmitButton: 'Submit',
    feedbackMissingError: 'Please enter some feeback'
};
//# sourceMappingURL=fr-FR.js.map